### ISSUE TITLE
How do you configure the downtime history chart?

### ISSUE THREAD

**Issue by bushong1** [cstate/cstate#105]
In the picture at the top of the readme, it shows a downtime history chart (similar to statuspage.io).  I've read through the wiki/docs but can't figure out how to create it, and none of the examples have it.  Am I missing something?  Thanks!  
![image](https://user-images.githubusercontent.com/236700/80599457-f4ca1300-89f8-11ea-9b00-55abd3f2b957.png)

**Comment by mistermantas** [comment]
![image](https://user-images.githubusercontent.com/11616378/80600760-8e171a80-8a35-11ea-87dd-6815cdde89f0.png)

If you're talking about this, this says "third party app". It's not a native feature, sorry.

**Comment by bushong1** [comment]
I see... is there a recommendation of what this third party app would be?  It is also kinda misleading to have this be one of the first things you see on the readme.

**Comment by mistermantas** [comment]
Okay, then this is a duplicate — #86.

The point is to show there's a third party service and honestly I don't know how to replace the illustration right now nor do I have the time to do so. It does have to look pretty, after all.

I believe I recommended https://uptimerobot.com/ or a similar service.

**Comment by bushong1** [comment]
Do you think it should be removed from the prominent picture on the readme?

**Comment by mistermantas** [comment]
> Do you think it should be removed from the prominent picture on the readme?

Unless there's a better alternative, I'm out of ideas, so no

**Comment by bushong1** [comment]
![image](https://user-images.githubusercontent.com/236700/80626307-3f10bb80-8a1c-11ea-8532-133d89996f00.png)
like this?

**Comment by HenrikBengtsson** [comment]
I'd also recommend to remove trim that one off the screenshot in the README because it's unfortunately misleading.  As a first timer, I've been looking around in the config files, the wiki, the demo site, the different real-world example sites to see what this could look like and how it is set up, but failed to find anything.  I was just to post an issue asking about this when I found this issue via some other issues.

**Comment by mistermantas** [comment]
I will be updating the README because the illustration just adds to the many things that are confusing.
