### ISSUE TITLE
Disable incident history

### ISSUE THREAD

**Issue by breucode** [cstate/cstate#107]
**Is your feature request related to a problem? Please describe.**
I would like to disable the incident history, as I do not need and and only want to show the current status of my systems.

**Describe the solution you'd like**
A config option (e.g. `enableIncidentHistory`), which completely disables the incident history including the RSS feed.

**Additional context**
I already prepared a merge request for that feature.

**Comment by mistermantas** [comment]
Make a PR, there's no 'dev' branch so you can do it for the master one.
