### ISSUE TITLE
Saving config from admin panel erases `enableCustomHTML` field

### ISSUE THREAD

**Issue by bushong1** [cstate/cstate#109]
**Describe the bug**
When saving via the admin panel, the `enableCustomHTML` field is erased.

**Reproduction steps**
1. Add `enableCustomHTML` to `config.yml`; commit to master
2. Make any change to the `config.yml` from `/admin`
3. Check PR to see that `enableCustomHTML` has been erased

**Expected behavior**
1. The setting isn't erased.

**Comment by mistermantas** [comment]
Thank you for the bug report, I'll continue the discussion for this on the PR.
