### ISSUE TITLE
Issue with headerTextColor

### ISSUE THREAD

**Issue by benoit74** [cstate/cstate#113]
**Describe the bug**
The parameter headerTextColor has no effect. When you set it to 'white', it does not alter the color of the page header.

**Reproduction steps**
1. Set params.headerTextColor = white in the config.yml
2. Open the website, the header is still black

**Expected behavior**
The header should be white

**Additional context**
According to my investigations, bug is already found and fixed, PR is already ready to be submitted in few minutes.

**Comment by mistermantas** [comment]
Thank you for the bugfix!
