### ISSUE TITLE
"affected" URLs does not end with a trailing slash

### ISSUE THREAD

**Issue by benoit74** [cstate/cstate#115]
**Describe the bug**
"affected" URLs (e.g. https://myhost.com/affected/mysystem) do not end with a trailing slash and it causes issues on my setup. Issues on another hand have the trailing slash (thanks to the usage of a permalink instead of a custom built URL) and are hence working perfectly well.

**Expected behavior**
From my understanding of the web standards, all URLs should have a trailing slash (to hence denote a kind of folder and let webservers look for the default index.html file. 

**Additional context**
A PR will follow soon.

**Comment by mistermantas** [comment]
I think, yeah, I need to add the trailing slash here, but:

1. what is your setup? i think the current system works with Netlify which just redirects to the correct place

2. In regards to:

> hence denote a kind of folder and let webservers look for the default index.html file

Hugo may have changed its behavior, but each file in "content/" has, when the site is finished generating, a folder. Basically, my point is that *everything* should have a trailing slash.

You can check if you look at the "public" folder of the demo site.

**Comment by benoit74** [comment]
1. nginx server with "default" configuration, i.e. the one in nginx:alpine Docker image
Indeed I achieved to fix the problem with a small nginx configuration adjustement :
`try_files $uri $uri/index.html =404;`

2. yes, I agree, everything is within a folder, and that's the reason why I believe that everything should end with a trailing slash.

**Comment by mistermantas** [comment]
thank you for your contribution! 🎉
