### ISSUE TITLE
Make every string translatable / changeable

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#12]
oh boy this is going to be fun.

if you have translation experience, give me a shout — either on this issue or by any other means.

**Comment by mistermantas** [comment]
This’ll be implemented as such;

```
data/
  lang/
    en.yml
```

```
{{ $lang := index .Site.Data.lang .Site.LanguageCode }}

{{ $lang.okMsg }}
```

**Comment by mistermantas** [comment]
This will now be in v3

if you are a translator — [see this](https://github.com/cstate/cstate/wiki/Translations#add-your-translations).

**Comment by mistermantas** [comment]
Lithuanian & English translations are finished, so I guess that’ll be the start!

**Comment by robsonsobral** [comment]
I always use native Hugo translations even for single language sites. To split the site into two, you have to set two languages on `config.yaml`.

It´s really easier to write `{{ i18n "okMsg" }}` than to define language variables on templates.

And you can have multiple languages, if you want to.

**Comment by mistermantas** [comment]
Alright, I'm sold. You make a good point. I'm not really sure if it's as, let's say, easy to set up / change around like how it is now though.

The data folder can easily let you change around the language files - create new ones, override them, etc

The config file is long as is

**Comment by mistermantas** [comment]
Unfortunetaly it looks like this isn’t going to work. The native multilingual mode is not ideal for this situation.

> Right now I quite like the structure of this project: `data/` has the language files, `config.yml` holds most of site-specific options (like whether to build posts with dates in the future, obviously the site title, what systems need to be tracked, etc) and mumbling that into one seems a bit counterintuitive.

Thanks for the reply nonetheless.

**Comment by robsonsobral** [comment]
I guess I need to explain better.

Please, take a look at this [project I worked on](https://github.com/AppCivico/DOnM-2017-www). The language files are [all inside `/i18n`](https://github.com/AppCivico/DOnM-2017-www/blob/master/i18n/pt.yaml), not `config.yaml`.

Only in case you want to load _more than one_ language, you need to set them on `config.yaml`, like I did on [this other one](https://github.com/AppCivico/pegabot/blob/master/config.yaml#L20).

Hugo stopped to recomend the `/data` for language translation a long time ago.

**Comment by mistermantas** [comment]
cState isn’t really a conventional Hugo website but, sure, I can give it a try.

Already, I can see the `i18n` folder’s language file is laid out differently. Case in point:

This is the current en.yml file:
```yml
thisIsDown: Down
thisIsDisrupted: Disrupted
thisIsNotice: Maintenance
thisIsOk: Operational
```

…and it would be a tad bit of work to re-do that. Not fun. But yeah, there’s quite a bit of cruft with the current solution.

**Comment by mistermantas** [comment]
I’ve given this a fair look — take a look yourself!
