### ISSUE TITLE
Showing local time automatically with JS - timezone conundrum

### ISSUE THREAD

**Issue by thuhole** [cstate/cstate#123]
**Describe the bug**
There seems no way to change the timezone in Netlify CMS. 
![image](https://user-images.githubusercontent.com/66957922/88513031-1a77b000-d01a-11ea-8fcb-07686e0c5c83.png)

When I create a new incident at https://xxxx.netlify.app/admin/#/collections/issues/new, it shows the local timezone(UTC+8, 2pm for example). However, when the incident is created, the UTC timezone time is shown on the status page website(6am in the example). 

When I checked the file generated in [GitHub repo](https://github.com/thuhole/status/blob/a2510fc84207599cf2a0416bcb580503f62dc646/content/issues/2020-07-27-test.md), the UTC timezone is written by Netlify. 

Is it possible to fix this?

**Comment by mistermantas** [comment]
This is a Netlify CMS thing.

Please make an issue on the Netlify CMS repo or reach out to the staff or whoever else who is more knowledgeable.

Though as a side note, I can change the default behavior.

Is this what you're looking for?

```
pickerUtc: (default: false) when set to true, the datetime picker will display times in UTC. When false, the datetime picker will display times in the user's local timezone. When using date-only formats, it can be helpful to set this to true so users in all timezones will see the same date in the datetime picker.


```

More:

https://www.netlifycms.org/docs/widgets/datetime/

**Comment by thuhole** [comment]
> This is a Netlify CMS thing.
> 
> Please make an issue on the Netlify CMS repo or reach out to the staff or whoever else who is more knowledgeable.
> 
> Though as a side note, I can change the default behavior.
> 
> Is this what you're looking for?
> 
> ```
> pickerUtc: (default: false) when set to true, the datetime picker will display times in UTC. When false, the datetime picker will display times in the user's local timezone. When using date-only formats, it can be helpful to set this to true so users in all timezones will see the same date in the datetime picker.
> ```
> 
> More:
> 
> https://www.netlifycms.org/docs/widgets/datetime/

Thank you for your reply!

The `pickerUtc` is not what I'm looking for. The problem is not how Netlify DISPLAY time in the UI, but how Netlify WRITE the time string to the file. Netlify would CONVERT any datetime to UTC time zone before writing to file.

So, the thing maybe is:
```
format: sets storage format; accepts Moment.js tokens; defaults to raw Date object (if supported by output format)
```
Maybe set the `format` "Moment.js tokens" to `YYYY-MM-DDTHH:mm:ss Z` or `YYYY-MM-DDTHH:mm:ss ZZ` would fix it?

**Comment by thuhole** [comment]
Another idea: is it possible to convert every time string in `content/issues/*.md` to the local time zone at the frontend website? Use javascript?

**Comment by thuhole** [comment]
> Another idea: is it possible to convert every time string in `content/issues/*.md` to the local time zone at the frontend website? Use javascript?

For example, if the .md file is:
```
---
section: issue
title: test
date: 2020-07-27T06:30:13.746Z
resolved: true
...
---
Investigating - We are investigating a potential issue that might affect the uptime of one our of services. We are sorry for any inconvenience this may cause you. This incident post will be updated once we have more information.
```
and the client is at UTC+8 time zone, the website should display: `14:30` or `2:30 PM` instead of `6:30`

**Comment by mistermantas** [comment]
I'm not sure if I am the best person to answer all these questions, actually, the Hugo support forum is also a really good place to ask about timezone formatting in the frontmatter -- especially in regards to the last comment since I haven't seen that personally

> Another idea: is it possible to convert every time string in `content/issues/*.md` to the local time zone at the frontend website? Use javascript?

I mean, I would say you'd have to either

1. change the dates in the files with Find & Replace or manually
2. change how dates are displayed in the code, with cState, without using JavaScript
3. JavaScript could work but I advise against using it, this is the worst of all the options.

If you are looking to change the CMS - config file, you can override the existing one by going to your site folder, then the static folder, then creating the admin folder, and then creating a new file called config.yml

Copy the default from here

https://github.com/cstate/cstate/blob/master/static/admin/config.yml

Then make your changes and see if that helps with the CMS UI.

**Comment by thuhole** [comment]
The JavaScript idea comes from the fact that: your clients accessing the website may come from different places in the world. Therefore the time displayed at the website shouldn't be static, it should be dynamic.

**Comment by mistermantas** [comment]
I get where you're coming from now.

My point is that the RSS and everything else will be UTC.

On the case that JS doesn't work, you need to make sure the timezone is
displayed - so UTC.

This is where just some text "(UTC)" would help lots. There's an option for
this - dateformat - in the main config.yml file. :)

UTC isn't *bad*, just inconvenient in some cases.

**Comment by thuhole** [comment]
Yes, I also support the UTC convention.

My thoughts are clear now.
I just want a feature that the time displayed at the website should be dynamic. For example, if you've got a client A at Singapore(UTC+8) and  client B at Greenwich. The system went down at 1PM UTC(which is 9PM UTC+8). The website would show that the system went down at 1PM. Then client B got everything correct but client A would believe that the system went down at 1PM, which is 8 hours earlier than the correct time.

The time displayed at the website MUST BE dynamic, this is the only correct way. So this is not a Netlify CMS thing, it is a cstate bug.

**Comment by thuhole** [comment]
In this way, just tuning the config files would never work.

**Comment by mistermantas** [comment]
A bug or an oversight by design then.

I operate in one time zone for example and I just enter mine manually into
the frontmatter.

To use dynamic time, everything should be UTC which, for some people, is
now what their frontmatters have.

So this is already an optional feature. Not that there aren't many like
this already.

I think status.io or whoever hosts the big status pages doesn't even do
dynamic time. They do show the time zone in the reported time though.

I would accept a PR and this is a good feature suggestion but I can't work
on it immediately.

**Comment by thuhole** [comment]
OK, I get you. I've checked [GitHub Status](https://status.github.com/), [Cloudflare Status](https://www.cloudflarestatus.com/), [Heroku Status](https://status.heroku.com/), they all use UTC display.

Now, the thing the very simple now. The only thing that needs to be done is to show a "UTC" in the time format. This can be done via config.yml.

Thank you for your kind replies!

**Comment by rocketnateynate** [comment]
This is still not resolved. I agree with the OP. It does no good to have the admin interface write an issue in UTC and display it in UTC when your audience is in EST or CST.  When the build happens, can you not pay attention to a TZ environment variable and update / display accordingly?  I am not a HUGO expert at all, nor a netlify one. But timezones seem like a very necessary config option especially when you are providing status updates. Seems like the core of the intended use of cstate.  

I should not have to go edit the .md files every time especially when you already provide a CMS to edit those. Just make them display correctly when loading the site.

**Comment by rocketnateynate** [comment]
After more thought: would solve my particular use-case if you just stored it in the issue.md in local format instead of UTC. The date picker is already in local time.

**Comment by rocketnateynate** [comment]
Just an update. I was able to solve this by 
- create static/admin/config.yml
- add `format: "YYYY-MM-DDTHH:mm:ss.SSS"` to the end of the `datetime` widget config. This saves the issue with my local time instead of UTC.

**Comment by mistermantas** [comment]
## Caveats

Looks like time zone support for Hugo is somewhat lacking:

https://github.com/gohugoio/hugo/issues/1882

So, like so many other features for cState, showing time zones automatically in the local time zone:

- Will be **opt-in for existing status pages**
- Will be **enabled by default on new sites**
- Will **require that all posts use UTC for dates in the front-matter**

## Example of date formatting moving forward

I looked at the exampleSite files and I found that the date at some point somehow had this markup:

> 2019-10-04 11:05:00 **-0700**

I'm assuming this is UTC-7.

On my end, that was rendered **October 4, 2019 at 6:05 PM** -- I am in Lithuania, should be UTC+3 (for the summer, UTC+2 later).

**I WILL CONTINUE TO RESEARCH DEFINING TIMEZONES, BUT FOR NOW...**

> 2019-10-04 11:05:00 UTC

...this should be the 'standard' way of doing it for all frontmatters.

## Implementation

The date on posts will be written like this:

> October 4, 2019 at 6:05 PM (your time) [?]
>
> _hovering [?] will show UTC_
>
> Oct 4 — 6:05 PM (your time)

**Comment by mistermantas** [comment]
@thuhole  Wait, Netlify CMS outputted this?

```
date: 2020-07-27 06:30:13 UTC
```


https://github.com/thuhole/status/blob/a2510fc84207599cf2a0416bcb580503f62dc646/content/issues/2020-07-27-test.md

That literally doesn't display properly for me with the "UTC" at the end on the demo site.

**Comment by mistermantas** [comment]
Support of the UTC convention is fully coming to v5. Follow progress: #151

What @rocketnateynate was described will not be fully supported from v5 onwards because without using UTC it is impossible to calculate relative time (as per the user's own time zone).
