### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by rocketnateynate** [cstate/cstate#125]
I can't seem to get the posts (issues) in cstate to show the correct Timezone.

I am using Netlify, deployed exactly like the Wiki describes. Very simple site. I just need the issues to show the real time instead of UTC.

I tried setting the `TZ` environment variable, both in the Netlify UI and in the `netlify.toml` file and neither worked. I am posting issues via the `cState Admin Panel`. 

Any advice here?  Seems like cstate is not paying attention to the build environment variables.

**Comment by rocketnateynate** [comment]
Just to add, I have also checked over the date formats specified in the documentation and am able to change that just fine, but it still shows UTC and I am in CST. The status pages cstate generates do me no good if the timezone cannot be correctly set.

**Comment by rocketnateynate** [comment]
See my comment in #123 on how I worked around this.

**Comment by mistermantas** [comment]
Not using UTC is not standard, but I'm glad you got it working. I'll look into this more.
