### ISSUE TITLE
THIS IS A SUPPORT ISSUE FOR @ANONYM-ANONYM

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#130]
> @mistermantas Hi, sorry that i am writing again to this issue. But I need help. I added css for iconify icons to head and i added iconify css icons to statuses in en.yaml file. But icons are not working :/ 
![20200927_165134](https://user-images.githubusercontent.com/70404616/94367932-c6ed1580-00e1-11eb-93cc-77a8549b2b2d.png)

_Originally posted by @ANONYM-ANONYM in https://github.com/cstate/cstate/issues/101#issuecomment-699645447_

**Anonym, please write in the proper place - this issue is for you so I can keep the category status issue strictly based on that topic. **

## Possible fixes

1. Try adding "" to the definitions, if there aren't any in the language file

2. It might be that the language file does not support HTML... I haven't checked. Another way to change the HTML is to override the template file.

Create a new file in your own layouts folder -

https://github.com/cstate/cstate/wiki/Customization#custom-html

If method 1 doesn't work, try method 2 - I can provide more details.

**Comment by ANONYM-ANONYM** [comment]
Hi, tried to add "" but it didnt work :/ 
Can you please add support for html in translations in a new release?

Also can you please show me more details how can i modify theme?

**Comment by mistermantas** [comment]
> Can you please add support for html in translations in a new release?

No, I literally can't do that even if I wanted to, that's up to the Hugo authors.

I will respond later with more instructions.

**Comment by ANONYM-ANONYM** [comment]
Also i have problem with status badge:
![20200930_202704](https://user-images.githubusercontent.com/70404616/94725006-679a3a00-035b-11eb-8e6f-1f8ab221c1ed.jpg)
Can you help me to fix it?

Also i have another suggest create individual status badges for systems

**Comment by ANONYM-ANONYM** [comment]
@mistermantas Can you please provide me more details how can i use css icons in translations if you will have time?

**Comment by mistermantas** [comment]
I mean, you _do_ know what the word "translations" means, right? A language file is not the place for icons.

You ought to modify the HTML:

https://github.com/cstate/cstate/wiki/Customization#replacing-other-partials

**This is a potentially destructive action. Do not attempt to do this unless you are a developer.**

I am assuming you mean you want icons on your homepage "All systems operational" bar.

1. Create a new file in your repository under the folders `/layouts/partials/index/summary.html`
2. Copy the contents of https://github.com/cstate/cstate/blob/master/layouts/partials/index/summary.html
3. Edit what you want to and you should see your results

**Comment by ANONYM-ANONYM** [comment]
@mistermantas Hi, idk what should i replace in https://github.com/cstate/cstate/blob/master/layouts/partials/index/summary.html
Here is what i want to change:
![image](https://user-images.githubusercontent.com/70404616/95086326-a72ca180-0720-11eb-82c2-53b8a325d989.png)

Also i have problem with resolved incidents:

![image](https://user-images.githubusercontent.com/70404616/95086804-33d75f80-0721-11eb-9436-74a13eeb88fb.png)

**Comment by ANONYM-ANONYM** [comment]
@mistermantas

**Comment by ANONYM-ANONYM** [comment]
Can you please help me to add custom css icons to cstate page? @mistermantas 

I want to replace these emojis with css icons:
![image](https://user-images.githubusercontent.com/70404616/95589309-dacf3a80-0a44-11eb-9cb9-d89db2333f80.png)

I added there emojis by changing i18n/en.yaml file. Now i want to replace emojis with css icons

**Comment by mistermantas** [comment]
> I mean, you _do_ know what the word "translations" means, right? A language file is not the place for icons or any HTML for that matter, that is why this didn't work.
> 
> You ought to modify the HTML:
> 
> [cstate/cstate/wiki/Customization#replacing-other-partials](https://github.com/cstate/cstate/wiki/Customization#replacing-other-partials)
> 
> **This is a potentially destructive action. Do not attempt to do this unless you are a developer.**
> 
> I am assuming you mean you want icons on your homepage "All systems operational" bar.
> 
> 1. Create a new file in your repository under the folders `/layouts/partials/index/summary.html`
> 2. Copy the contents of [https://github.com/cstate/cstate/blob/master/layouts/partials/index/summary.html](https://github.com/cstate/cstate/blob/master/layouts/partials/index/summary.html?rgh-link-date=2020-10-03T15%3A18%3A57Z)
> 3. Edit what you want to and you should see your results


Read this again.

You need to override the template, sir.

```html
  <strong>
    {{ if $isDown }}
      ICON {{ T "isDown" }}
    {{ else }}
    {{ if $isDisrupted }}
      ICON {{ T "isDisrupted" }}
    {{ else }}
    {{ if $isNotice }}
      ICON {{ T "isNotice" }}
    {{ else }}
      ICON {{ T "isOk" }}
    {{ end }}{{ end }}{{ end }}
  </strong>
```

Please do not use CSS with the translation file.

The translation file is for translations.
