### ISSUE TITLE
Macedonian Translations

### ISSUE THREAD

**Issue by krisfremen** [cstate/cstate#140]
**Is your feature request related to a problem? Please describe.**

I would like to translate cstate into Macedonian.

**Describe the solution you'd like**

A Pull Request from me with a new locale(mk) for the Macedonian Language.

**Describe alternatives you've considered**

I can translate to a few other languages for alternatives :smile: 

**Additional context**

N/A

**Comment by krisfremen** [comment]
Pull request is up for review.

Happy hacktoberfest!

Cheers!

**Comment by mistermantas** [comment]
Hi! If you can make more translations later, I'd be happy to merge them, too!
