### ISSUE TITLE
Error when using Netlify CMS

### ISSUE THREAD

**Issue by Sarveshmrao** [cstate/cstate#144]
**Describe the bug**
When using Netlify CMS Dashboard the `untitled` is changed as `untited` in the config.yaml and hence the Uncategorized category is not invisible. 

**Reproduction steps**
Steps to reproduce the behaviour:
1. Go to Netlify CMS Dashboard
2. Click on Settings>Configuration File
3. Scroll down to CATEGORIES
4. Make a new category or edit an existing one
5. Enable the `SHOULD THE NAME OF THIS CATEGORY BE SHOWN? IF YOU WANT TO CREATE THE APPEARANCE OF AN UNCATEGORIZED CATEGORY, ENABLE THIS. (OPTIONAL)` toggle.
6. Go to GitHub config.yaml file and scroll to the category.
7. As per the customisation it should be `untitled` but it is `untited` 'l' is missing. 
8. Which causes the category title to be visible. 
9. When I manually change it to `untitled` it works as intended!

**Expected behaviour**
The category title should be invisible.

**Screenshots**
No screenshots.! Sorry for that. 

**Additional context**
I have explained everything above.

**Comment by mistermantas** [comment]
Oh, this issue is much simpler than I thought, it's `untited` instead of `untitled` in the Netlify CMS config.


Thanks for bringing up the issue!

**Comment by Sarveshmrao** [comment]
@mistermantas is this rectified?

**Comment by mistermantas** [comment]
> @mistermantas is this rectified?

No. You would have to update to a release where this issue is fixed, that's coming soon, but not right now


your current option is to override the file in your own site for now

**Comment by Sarveshmrao** [comment]
Ok thanks!

**Comment by Sarveshmrao** [comment]
This issue is corrected with PR #149
