### ISSUE TITLE
Hosting on gitlab pages

### ISSUE THREAD

**Issue by wolfier74** [cstate/cstate#158]
Hello, can you please make and add to wiki  setup guide how to host cstate on gitlab pages. I want to use also netlify cms there

**Comment by mistermantas** [comment]
https://github.com/cstate/cstate#-gitlab-pages-experimental

I'm sorry, but I do not use GitLab, so I'm not sure, if I can help more than this.

**Comment by wolfier74** [comment]
Oh, please send me what to change in config file

**Comment by mistermantas** [comment]
> Oh, please send me what to change in Netlify CMS config file

I don’t understand?

**Comment by wolfier74** [comment]
I mean that i dont know what should i change in netlify CMS config file (static/admin/config.yml)

**Comment by mistermantas** [comment]
Why do you want to change that file?


________________________________

**Comment by wolfier74** [comment]
Because i want to use dashboard (Netlify CMS) for my statuspage

**Comment by mistermantas** [comment]
Oh, I hope I understand now.

https://www.netlifycms.org/docs/gitlab-backend/

You have a cState instance on GitLab.

You want to use netlify cms with that instance.

I attached a link to the official docs of the cms dev.
