### ISSUE TITLE
Add JSON to affected

### ISSUE THREAD

**Issue by Saganic** [cstate/cstate#159]
**Is your feature request related to a problem? Please describe.**
Yeah, I need a way to query each system for its issues. I can't seem to do that with the current API implementation.

**Describe the solution you'd like**
To be able to query each system for its issues. Something like https://example.org/affected/system-name/index.json

**Describe alternatives you've considered**
The current alternative is to query and parse the XML

**Comment by mistermantas** [comment]
This is indeed not a thing. Actually, I didn’t find any list type JSON template, so for niw you might have to make do with xml.

Is there anything you would want added specifically to the json file for the next release?

**Comment by Saganic** [comment]
> This is indeed not a thing. Actually, I didn’t find any list type JSON template, so for niw you might have to make do with xml.
> 
> Is there anything you would want added specifically to the json file for the next release?

Thanks for the quick response on this @mistermantas. 

Realistically, just a list of each system's issues is fine.

The other thing (sorry if unrelated) is that it would be useful to have the unresolved issues list detailed on the   https://example.org/index.json, perhaps as an array on the system object itself.

**Comment by mistermantas** [comment]
>  The other thing (sorry if unrelated) is that it would be useful to have the unresolved issues list detailed on the https://example.org/index.json, perhaps as an array of unresolved issues on the system objects themselves.

Had this thought too, actually surprised I didn't implement it the first time around.

**Comment by mistermantas** [comment]
API v2 for v5 dev:

* example.com/index.json (homepage) now shows **category status and category's unresolvedIssues**
* for all issues (`is: issue`) the `informational` variable is now a boolean true/false. no more `<no value>`
* likewise, the `resolved` variable is no longer a string surrounded by "", but an actual boolean
* added lastmod to issues
* there is generally less whitespace
* added tab links
* reordered to have more important info up top

I have added a list-type json file to show for ALL ISSUES (example.org/issues/list.json)

Having some difficulty at the time of writing to get the affected taxonomy to output JSON files for some reason, but I'm committed to making this work

Follow progress on PR #151 

Thanks for using cState (past or present)!
