### ISSUE TITLE
Docker instance only shows nginx welcome

### ISSUE THREAD

**Issue by Audition-CSBlock** [cstate/cstate#160]
When I follow the docker instructions from the wiki it just takes me to the nginx welcome page.

**Reproduce**
1. Follow current wiki on docker install
2. run it with either volume or mount
3. go to localhost:8080
4. see error

**Expected behavior**
I expect to see the same output that i would get from manually building it with hugo.

**Server**
 - OS: Linux Ubuntu 20.04

**Logs**
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/10-build-hugo.sh, not executable
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

**Additional context**
I may have read the wiki wrong, if i did, please, do not tell me to "read it again". Instead, you could tell me what i forgot to read that was stated somewhere in the wiki or provide a fixed command. This is also much more useful to people with the same problem and wasting lots of time trying to search the web.

Thank you in advance.

**Comment by mistermantas** [comment]
Hi, Docker is not really officially supported. If my colleagues can help, he will reply

**Comment by Audition-CSBlock** [comment]
@mistermantas Ah, i will wait for that then. In the meantime, is there any guide on how to fully customize cstate?
In a sense that when i add a new service to track; where do i put the link for cstate to track it?

**Comment by mistermantas** [comment]
I'm sorry i'm not sure what you're talking about? Check the Wiki.


________________________________

**Comment by Nevexo** [comment]
Hi! I'll get on this tomorrow morning, looks like some volume mount is failing, or we might have a problem in the script. 

Thanks for your patience 👍

**Comment by Audition-CSBlock** [comment]
@Nevexo Don't thank me for my patience, I should thank you guys for helping! Just a little disappointed in myself that I couldn't figure it out on my own haha.

**Comment by mistermantas** [comment]
> is there any guide on how to fully customize cstate? In a sense that when i add a new service to track; where do i put the link for cstate to track it?

I'm not sure whether you found the solution you were looking for, but there is no automatic tracking built in.

https://github.com/cstate/cstate/wiki

**Comment by Audition-CSBlock** [comment]
@mistermantas is there a method on how to integrate that into cstate?

**Comment by Nevexo** [comment]
Apologies for the delay on this, university. 😒

I've opened a PR (#162) that should resolve this, if you're able, please clone my fork (https://github.com/Nevexo/cstate) and checkout the patch-docker branch to test this fix. There's still improvements to make with the cState docker images, but I've outlined these issues in the PR.

Hope this helps, 
Nev.
