### ISSUE TITLE
Custom CSS with Netlify

### ISSUE THREAD

**Issue by Hxnry890** [cstate/cstate#163]
Hello,

Where I can make completly customized pages, when I'm using Netlify deploys? Is it on github or i need to find custom html pages at Netlify?

**Comment by mistermantas** [comment]
No, you need to edit estate content and layouts. Netlify is irreelevant.

ses cstate and gohugo.io wikis

Why do you need custom pages on a status page anyway? Make a dedicated site.

**Comment by Hxnry890** [comment]
I want to use my own css at status pages. Thanks for sending wiki

**Comment by mistermantas** [comment]
> I want to use my own css at status pages. Thanks for sending wiki

ah, yes, look for custom html in the wiki 👍
