### ISSUE TITLE
clarify "cState & Hugo don’t support / in production use"

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#164]
**Is your feature request related to a problem? Please describe.**

I get confused by this warning in the wiki:

> cState & Hugo don’t support / in production use

... which is also present in the `config.yml`  template. What does it mean? It doesn't like *trailing* slashes in the `baseURL`? setting?

Then why is the example with a trailing slash? :)

```
# What is the hostname or path to the root?
# Where is the site hosted?
#
# ❗ cState & Hugo don’t support '/' in
# production use. It will break RSS
# feeds and breaks permalinks since
# version 3. If you are just testing,
# localhost should automatically work.
#
# Example: https://status.example.com/
baseURL: http://localhost/
```

**Describe the solution you'd like**

I would suggest clarifying *which* slash is "unsupported" (and possibly why?). at least make an example that doesn't break RSS, for example.

At least here the trailing `/` is not a problem so i'm still confused as to what the solution is.

**Describe alternatives you've considered**

I added the trailing slash, haven't tried removing it, and RSS feeds work.

**Additional context**

Sorry for my confusion, I hope this is clear enough. :)

**Comment by mistermantas** [comment]
This does not work:

`/`

This works:

`https://example.com/` (although it is kind of ugly with the trailing slash)

Base URL is supposed to not be empty basically. OBVIOUSLY it can have slashes there, the problem is not the symbol itself, but what you put inside of the value.

RSS feeds should have the base url + relative link to article. So imagine a permalink that has no domain. It won’t work for RSS readers. Probably. Not a big RSS guy myself, but that solution seemingly has stood the test of time.

Is this clear? How should I change the docs?

**Comment by anarcat** [comment]
> OBVIOUSLY it can have slashes there, the problem is not the symbol itself, but what you put inside of the value.

See, that wasn't obvious to me at all. It may be, for people familiar to hugo, but i come from the other side, where i'm a sysadmin with only passing experience with hugo, looking for just a tool. :)

> RSS feeds should have the base url + relative link to article. So imagine a permalink that has no domain. It won’t work for RSS readers. Probably. Not a big RSS guy myself, but that solution seemingly has stood the test of time.

That totally makes sense, thanks. I'm a fan of RSS, and I think it's super useful that cState has support for it - please keep it! :)

> Is this clear? How should I change the docs?

Much clearer. :) How about explicitely saying just what you said:

> 
> This does not work:
> 
> `/`
> 
> This works:
> 
> `https://example.com/` (although it is kind of ugly with the trailing slash)

You could even expand it to say that you need a complete URL, with the `https` and address parts... 

Does that make sense?

**Comment by anarcat** [comment]
maybe #165 would be enough? along with an update in the wiki and a sync on the example project, i guess...

**Comment by mistermantas** [comment]
Syncing is only done with new releases, not new commits.

Also mind that I might have to clarify on Netlify CMS also.

Thanks for bringing this up, I’ll get to it when I can.

**Comment by anarcat** [comment]
> Also mind that I might have to clarify on Netlify CMS also. Add a link to hugo docs maybe.

feel free to update the PR, I somewhat need to move on and figured I'd give feedback on my user experience. :)
