### ISSUE TITLE
warnings during build

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#167]
**Describe the bug**

I'm getting this warning while building the site with `hugo`:

```
Found no layout for "section", language "en", output format "JSON"[...]
```

**Reproduction steps**
1. clone this repository: `git clone --recursive -b main https://gitlab.torproject.org/tpo/tpa/status-site.git`
2. build the site: `cd status-site; hugo`
3. see warning

This also occurs when cloning the example site:

    git clone --recursive -b master https://github.com/cstate/example.git

**Expected behavior**

The site should build cleanly and without errors.

**Screenshots**

This is the actual behavior I get.
```
anarcat@angela:status-site(main)$ hugo
Building sites … WARN 2021/01/25 17:33:36 Found no layout for "section", language "en", output format "JSON": create a template below /layouts with one of these filenames: issues/issues.en.json.json, issues/section.en.json.json, issues/list.en.json.json, issues/issues.json.json, issues/section.json.json, issues/list.json.json, issues/issues.en.json, issues/section.en.json, issues/list.en.json, issues/issues.json, issues/section.json, issues/list.json, section/issues.en.json.json, section/section.en.json.json, section/list.en.json.json, section/issues.json.json, section/section.json.json, section/list.json.json, section/issues.en.json, section/section.en.json, section/list.en.json, section/issues.json, section/section.json, section/list.json, _default/issues.en.json.json, _default/section.en.json.json, _default/list.en.json.json, _default/issues.json.json, _default/section.json.json, _default/list.json.json, _default/issues.en.json, _default/section.en.json, _default/list.en.json, _default/issues.json, _default/section.json, _default/list.json

                   | EN  
+------------------+----+
  Pages            | 19  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  9  
  Processed images |  0  
  Aliases          |  5  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 13 ms
```

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Browser: Firefox, but not 
 - Version: hugo 0.55.6+really0.54.0-1 from debian packages

**Comment by mistermantas** [comment]
this isn't really a big deal and it's not your fault - just need to edit the default config file to remove the warning or create that layout hugo wants

**Comment by mistermantas** [comment]
marking this as duplicate since to fix it I need to either make a new template (which I will do because somebody requested it and I'm surprised I didn't do it earlier - https://github.com/cstate/cstate/issues/159) or to ask users of cState to change their config.yml which I don't want to do.
