### ISSUE TITLE
Feature request - last modified - last updated field vs issue start time

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#168]
One of our first users here did the "mistake" of using the `date` field as when the issue was reported (or last updated) as opposed to when the outage started. Basically, they wrote:

    ---
    title: Disruption of v3 onion services and consensus building
    date: 2021-01-28 13:23:00
    resolved: false
    # Possible severity levels: down, disrupted, notice
    severity: disrupted
    affected:
      - directory authorities
      - v3 services
    section: issue
    ---

    We're currently facing [stability issues](https://lists.torproject.org/pipermail/network-health/2021-January/000661.html) with respect to our v3 onion services and consensus building. We are actively working on resolving those issues as soon as possible.

    Start time of this incident was around 2300 UTC on 01/27/2021.

Notice how they felt the need to indicate the `Start time of the incident`, even though cState considers the `date` field to be that date, as far as resolution times are concerned. I suggested [the following patch](https://gitlab.torproject.org/tpo/tpa/status-site/-/merge_requests/2) to correct the situation, but then realized there was no date field for the date they were trying to express.

Which is, basically, "when this issue was last updated".

**Describe the solution you'd like**

Maybe this could be another field (`updatedDate`? kind of a mouthful...) that more clearly indicates when the issue was last modified. Or, even better, couldn't Hugo compile this for us automatically?

It would also help if cState would clearly show what the date is in the rendered version, to avoid any confusion.

Thanks for this great software!

**Comment by mistermantas** [comment]
I get the purpose of having a last updated field, but I assumed you would write in the body when you have any new information.

Consider using hugo's lastmod git info:

https://discourse.gohugo.io/t/rendering-lastmod-date/13968

https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/

https://discourse.gohugo.io/t/adding-last-modified-git-status-to-pages/25402

Does this help?

Also note this might not work on hugo server -- I've tried using something similar before.

**Comment by anarcat** [comment]
> I get the purpose of having a last updated field, but I assumed you would write in the body when you have any new information.

That makes sense when you update the issue, but what about when you just wrote it?

I'm not super familiar with hugo itself... would adding `lastmod` to the front matter be sufficient here? would it render in the template? or add `enableGitInfo = true` to config.toml? i'm a bit confused as to what works in hugo and what works in cstate, to be honest...

**Comment by mistermantas** [comment]
lastmod is automatic. You do not need to add it to the frontmatter. Instead you need to edit a layout/template file.

I believe the last modified date shows up from Git, if you're using that, after you build/compile the site.

I can show you if you'd like

**Comment by anarcat** [comment]
> I can show you if you'd like

I guess that's what I'm asking here: can we add this to the cState templates directly?

Basically, I would need to add `{{ .Lastmod.Format "January 2, 2006" }}` to... what? i don't see the current dates in `themes/cstate/layouts/issues/single.html`...

> hugo is the CMS (SSG), while cstate is the theme, technically, it's the thing built on top of hugo, it's reliant on it

Yeah, i figured out that part, thanks. :)

**Comment by mistermantas** [comment]
**do not go inside themes/**

override the files instead in your own directory

this way you can update in the future to a better cState version (lots of PRs if you were to look, are in the pipeline)

![image](https://user-images.githubusercontent.com/11616378/106506179-07b2cc00-64d2-11eb-8c29-96c9fb26e7e0.png)

go to this file: https://github.com/cstate/cstate/blob/master/layouts/issues/issue.html

the `single.html` file asks to render from the `issue.html` template:

```html

    <div class="contain">
      {{ .Render "issue" }}
    </div>

```

**Comment by mistermantas** [comment]
also I recommend specifying: this issue was created {{ .Date }}... and it was last modified {{ .Lastmod }} (an example!)

**Comment by anarcat** [comment]
> do not go inside themes/

.. but then how to i contribute the fix back to cState?

**Comment by mistermantas** [comment]
Don't worry about that, I will mark this issue as a feature req.

new version isn’t coming out soon + you need to get this working for you now

**Comment by anarcat** [comment]
thanks!

**Comment by anarcat** [comment]
> new version isn’t coming out soon + you need to get this working for you now

i've been looking around, and it seems there's way more places than i'd expect where the date would need to be changed:

```
anarcat@curie:status.torproject.org(use-date)$ rg Date.Format
config.yml
170:  # Technical: GOLANG/HUGO .Date.Format & dateFormat

themes/cstate/exampleSite/config.yml
153:  # Technical: GOLANG/HUGO .Date.Format & dateFormat

themes/cstate/layouts/index.xml
12:      <lastBuildDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</lastBuildDate>
24:          <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>

themes/cstate/layouts/_default/list.xml
10:    <lastBuildDate>{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</lastBuildDate>
11:    <updated>{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</updated>
22:        <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>

themes/cstate/layouts/issues/issue.html
15:      {{ .Date.Format .Site.Params.dateFormat }}
17:      {{ .Date.Format "January 2, 2006 at 3:04 PM" }}

themes/cstate/layouts/issues/small.html
13:        {{ .Date.Format .Site.Params.dateFormat }}
15:        {{ .Date.Format "January 2, 2006 at 3:04 PM" }}
28:        {{ .Date.Format .Site.Params.dateFormat }}
30:        {{ .Date.Format "January 2, 2006 at 3:04 PM" }}
72:        {{ .Date.Format .Site.Params.dateFormat }}
74:        {{ .Date.Format "January 2, 2006 at 3:04 PM" }}

themes/cstate/layouts/partials/index/incidents-monthly.html
8:  <p class="center" id="archive-{{ range first 1 .Pages }}{{ .Date.Format "2006" }}{{ end }}-{{ .Key }}"><a href="#archive-{{ range first 1 .Pages }}{{ .Date.Format "2006" }}{{ end }}-{{ .Key }}" class="no-underline">
15:        {{ $monthDate.Format "January" }}
19:        {{ $monthDate.Format "January" }}
21:      {{ range first 1 .Pages }}{{ .Date.Format "2006" }}{{ end }}
```

It seems I'd need to take each one of those one by one and figure out how to integrate an extra field without breaking the layout. HTML integration is not my forte, so I guess i'll just wait for the release for now. But thanks for the pointers! :)

**Comment by mistermantas** [comment]
In v5 (or probably any future version) I'm not changing .Date -- it is staying as the variable for "when this issue was created at".

However, `lastMod` is now available through the v2 API and I am trying to figure out how to implement it properly in the UI. There's a param in config.yml `enableLastMod` if you want to check it out.

I did notice one thing while researching this which was that **if no .Date is defined, the fallback is the Git last modified date**. Which might be _a_ solution, but not the best one, still, not something I'd recommend.

**Comment by mistermantas** [comment]
Also, XML will show lastmod now:

`    <updated>{{ .Lastmod.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</updated>`
