### ISSUE TITLE
archetype support

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#169]
**Is your feature request related to a problem? Please describe.**

Creating a new issue in cState is somewhat error-prone. While the [documentation](https://github.com/cstate/cstate/wiki/Usage#creating-incidents-method-1) for this is pretty good, people have this unfortunate tendency of ... well, not reading documentation at all, particularly in times of dread and need and despair, which is often when cState is used.

**Describe the solution you'd like**

It would be great if cState would ship with a template with examples of the various fields "issues" support. I recently learned about [Hugo Archetypes](https://gohugo.io/content-management/archetypes/) which seem to be the perfect match for this.

Then creating an issue is just a matter of calling:

    hugo new issues/2021-02-03-testing-cstate-again.md

**Describe alternatives you've considered**

An alternative would be to just have a regular template.md file sitting in the `content/issues/` directory and that people copy/paste that manually, but where's the fun in that!

Obviously, people might not know about the archetype feature, but it gives us a better chance at it. And worst case, people can also copy-paste the thing from the archetype directory... There's some discoverability there, in other words.

**Additional context**

I found out about this feature in a [wider discussion about templates and markdown in the Hugo forum](https://discourse.gohugo.io/t/updating-archetype-instances-after-use/31020).

**Comment by mistermantas** [comment]
I'm glad you're interested in using more of hugo and its features as well as contributing your ideas!

I haven't used archetypes so I'd have to look into them a bit more and get back to you, however... I think there are example issues.

When you first copy the example site, there's quite a few of them contents folder.

It's possible to add `draft: true` to the frontmatter if you do want a _template.md which is probably easier.

I cannot calculate what percentage of users rely on Netlify and Netlify CMS, for example, and which rely on the actual file system.

I'm not sure if I can make documentation any better, if I can someway, let me know

**Comment by anarcat** [comment]
> It's possible to add draft: true to the frontmatter if you do want a _template.md which is probably easier.

Oh, that's good to know.

So I think that "supporting archetypes" would simply be a matter of dropping a template file (ideally with all fields relevant to cState present) in `archetypes/issues.md` or `themes/cstate/archetypes/issue.md` and...

Oh. There's already an archetype, right there, in `themes/cstate/archetypes/default.md`. :) Uh. Okay, sorry for the noise! :)

**Comment by anarcat** [comment]
Hum... I guess one improvement here could be to ensure the documentation mentions archetypes and `hugo new`? not sure how far we want to be holding hands for people discoverying hugo...

I'll certainly add it to our sysadmin docs in any case. :)
