### ISSUE TITLE
[Feature request] Selecting systems in categories during outages

### ISSUE THREAD

**Issue by cachedout** [cstate/cstate#170]
**Is your feature request related to a problem? Please describe.**
I have a configuration structured as such:
```
 categories:
   - name: a
   - name: b
   - name: c
  systems:
    - name: x
      category: a
    - name: x
      category: b
    - name: x
       category: c
```
This renders correctly in the according menus on the main page (yay!) but so far as I can tell, it is not possible to select a system by category when making an outage report. If `a` is selected, then the system `a` in all categories will be reported as down, which may not be what I intend to show.

**Describe the solution you'd like**
I would like to be able to have a configuration where a system may appear in multiple categories and then, that specific system may be targeted when creating an outage report. A sample report might appear like:

```
---
title: Sadness for the x system in the c category
date: 2021-02-08 14:30:00
resolved: false
severity: down
affected:
  - b:
    - x
section: issue
---

We are looking into this...
```

**Describe alternatives you've considered**
I can apply distinct names for each system in each category (which is what I'm doing now), but being able to do as described above would map more naturally to what I'm trying to achieve, which would be to have the same type of service deployed in multiple categories but be able to target them independently.

**Additional context**
I'm not married to the YAML in my proposed solution above. Anything that achieves the goal of being able to name a system the same thing in multiple categories and then target them distinctly would be great!

**Comment by mistermantas** [comment]
Thanks for the suggestion, but this is outside of the scope of this project and it seems like too complex for this rather simple project to be supported.

I should also note there was a similar request opened **2 years ago** with complex YAML like this - https://github.com/cstate/cstate/issues/47 - and it's stale. It's not the YAML itself that's hard to make, but the actual templating for hugo to use. I'm not an expert on this, so if someone wants to work on this - please do, I cannot promise this though.
