### ISSUE TITLE
Netlify CMS config.yml does not pass YAML validation

### ISSUE THREAD

**Issue by gabrielgunnarsson** [cstate/cstate#178]
**Describe the bug**
Current version of the config.yml for Netlify CMS does not pass YAML validation. This results in an exception when trying to access the CMS Admin interface.

**Additional context**
The error differs depending on the parser you use, yamllint.com says: "did not find expected key while parsing a block mapping at line 104 column 9"

**Comment by mistermantas** [comment]
Will fix ASAP.
