### ISSUE TITLE
affected/404 template not built

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#183]
**Describe the bug**

The `affected/404.html` template doesn't get built on our configuration, which leads to the regular 404 page kicking in when people click on components without incidents.

**Reproduction steps**
1. Go to <https://status.torproject.org/>
2. Click on [Onion v3 services](https://status.torproject.org/affected/v3-onion-services/)
3. See 404 error

Another way to reproduce this is to just visit <https://status.torproject.org/affected/404> which should be the "affected"-specific 404 page but instead triggers the ErrorDocument and the default 404.

**Expected behavior**

`hugo` should build the `affected/404.html` page, but doesn't:

```
anarcat@curie:status.torproject.org(main)$ hugo 
Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 21  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  9  
  Processed images |  0  
  Aliases          |  6  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 68 ms
anarcat@curie:status.torproject.org(main)$ qfind 404
./.git/objects/a7/3074c3a23e07e1b847c87404f108f4dbb58f12
./public/404.html
./themes/cstate/layouts/404.html
./themes/cstate/layouts/affected/404.html
anarcat@curie:status.torproject.org(main)$
```

**Comment by mistermantas** [comment]
Can't reproduce.

![D4032896-807C-40E6-8B06-3E7BA5AF6838](https://user-images.githubusercontent.com/11616378/117307319-22a62b00-ae89-11eb-8370-5b9a072da01a.png)

**Comment by anarcat** [comment]
> I can't reproduce this?

You're hitting the /404.html page, which I setup a ErrorDocument for, not the /affected/404.html page. As far as I know, those two are different, aren't they?

And I would expect the `affected/404.html` page to be created in `public/` when running hugo, can you not reproduce that as well?

**Comment by mistermantas** [comment]
I tried these and got 404s:

https://status.torproject.org/affected/torproject.org/
https://status.torproject.org/affected/tor-check/
https://status.torproject.org/affected/tor-check/

and https://status.torproject.org/affected/v3-onion-services/ which now has issues on it so it's not supposed to be a 404.

Am I missing something? Maybe this is only broken for Tor client users?

**Comment by mistermantas** [comment]
> And I would expect the affected/404.html page to be created in public/ when running hugo, can you not reproduce that as well?

Also, I believe hugo which powers cstate has just one 404.html file in the root which is automatically applied to all links that need to show a 404. Netlify et al automatically notice this file and use it, if you're using a platform that I'm not aware of it or isn't built for cState (I don't test on nginx, e.g.), then it could be different

**Comment by anarcat** [comment]
> Am I missing something? Maybe this is only broken for Tor client users?

Maybe I'm not expressing myself clearly.

Yes, you are getting 404s for those pages, but not the *right* 404s. You are getting the base 404.html file, because I have this in the Apache virtual host:

```
	ErrorDocument 404 /404
```

From what I understand after reading https://github.com/cstate/cstate/issues/183, there should be a *different* 404 page for the `affected/` area.

> Also, I believe hugo which powers cstate has just one 404.html file in the root which is automatically applied to all links that need to show a 404. Netlify et al automatically notice this file and use it, if you're using a platform that I'm not aware of it or isn't built for cState (I don't test on nginx, e.g.), then it could be different

What is this file for then? https://github.com/cstate/cstate/blob/master/layouts/affected/404.html

you seem to be thinking this bug report is basically "404 pages do not work". That is not the case: this bug report is "404 pages do work, but not affected/404". :)

**Comment by mistermantas** [comment]
That is quite a bit different indeed, apologies on my part. But in practice 404.html is identical to affected/404.html -- they use:

```
    <div class="contain center">
      <h1 class="bold">{{ T "notFoundAffected" }}</h1>
      <p>{{ T "notFoundText" }}</p>
    </div>
```

...which says that it "is also possible that the resource you are trying to view is empty" which hints at why clicking upon a system/component you might see a 404.

A fix (if this is an issue) would be a better description for the notFoundText string in the language file.

**Comment by anarcat** [comment]
that's not what I see here:

```
anarcat@curie:status.torproject.org(main)$ diff -u themes/cstate/layouts/404.html  themes/cstate/layouts/affected/404.html 
--- themes/cstate/layouts/404.html	2021-01-19 16:24:29.388164663 -0500
+++ themes/cstate/layouts/affected/404.html	2021-01-19 16:24:29.388164663 -0500
@@ -11,7 +11,7 @@
     {{ partial "header" . }}
 
     <div class="contain center">
-      <h1 class="bold">{{ T "notFound" }}</h1>
+      <h1 class="bold">{{ T "notFoundAffected" }}</h1>
       <p>{{ T "notFoundText" }}</p>
     </div>
 
```

ie. they *do* differ, at least in theory. In practice, the latter just doesn't get built at all (which is the whole point of this bug report ;).

Also, they don't differ *much*: if this gets fixed, it might be worth making the latter (the affected version) more suited for the section.

**Comment by mistermantas** [comment]
Silly me, right there's notFound and notFoundAffected (`It looks like this system either does not exist or has never had any recorded downtime.`)

If I had to guess, hugo doesn't build such things for... some reason.

Will look into this for possible fixes.

**Comment by anarcat** [comment]
i'm glad I was able to clarify this, and relieved that it's a bug in cstate/hugo and not in my head. i was going crazy out here. :)
