### ISSUE TITLE
"Experiment running" et al modifications -- document possibilities?

### ISSUE THREAD

**Issue by gk-tpo** [cstate/cstate#189]
**Is your feature request related to a problem? Please describe.**

We don't want to have only issues on our status page but something like the state of currently ongoing experiments as well. However, the incidents-driven language does not really fit to that use-case which is why we needed to come up with additional labels.

**Describe the solution you'd like**

I created an additional content category, experiments, which needs some additional labels so our experiments status is useful to our users.

**Describe alternatives you've considered**

I tried to use existing labels but did not find any that were working for us.

**Additional context**

I've created a [branch in our Gitlab repo](https://gitlab.torproject.org/gk/cstate/-/commits/strings_for_experiments) showing the proposed changes. Additionally, you can see the behavior at our [status page](https://status.torproject.org/) at the "Network Experiments" section.

Let me know what you think. I am  happy to submit a proper PR if the branch above is not enough but we'd be happy to get the proposed changes (or similar ones) upstreamed so we don't need to maintain a fork forever and other users can easily adapt their status pages respectively, too.

**Comment by mistermantas** [comment]
Have you tried informational posts? I don't know if they are in the wiki

**Comment by mistermantas** [comment]
https://github.com/cstate/cstate/releases/tag/v4.0.0

**Comment by gk-tpo** [comment]
> Have you tried informational posts? I don't know if they are in the wiki

I just looked at them. Thanks for the pointer. I think the informational posts idea is nice but it seems I can't make it work with our requirements without any modifications to `cstate`:

1. We want to show whether experiments are running or not on the frontpage showing a status summary ("Ongoing"/"None" currently).
2. If one is looking closer at the experiments we are currently running/were running in the past then the former should get some hint that they are indeed currently running ("This experiment is still ongoing" vs. just an omission of that note if it is not running (anymore).

I've been looking at the contents of `en.yaml` again but found no strings that would give good hints for 1. and 2. above. I am happy to work on the wording so that those string might be useful for other folks as well (for instance I got the feedback that instead of "Ongoing" we might want to use "Active", as "Ongoing" could just mean "yes, XYZ is sometimes happening").

**Comment by mistermantas** [comment]
have you considered using custom html for this?

https://github.com/cstate/cstate/wiki/Customization#custom-html

I'm not sure what kind of placement would work best for you, I can update cState to add new custom html capabilities but don't want to add new strings that would go untranslated (or Google translated) and might add some unnecessary complexity

Let me know if custom HTML could work in this case

**Comment by gk-tpo** [comment]
> have you considered using custom html for this?

Not so far.
 
> https://github.com/cstate/cstate/wiki/Customization#custom-html
> 
> I'm not sure what kind of placement would work best for you, I can update cState to add new custom html capabilities but don't want to add new strings that would go untranslated (or Google translated) and might add some unnecessary complexity
> 
> Let me know if custom HTML could work in this case

Hrm. I am not sure I understand how this would help with us needing custom *new* strings which are not available in `cstate` yet. Could you elaborate?

I think what would be really helpful as a feature request is being able to amend the strings you provide in the `i18n` folder with own ones. All the layout parts are overlay-able which is very nice, just the localization part seems hard to be customizable. I would not propose to being able to overlay that one similar to the layout case. But amending the already available strings with custom ones seems to be very useful (not just for our case).

**Comment by mistermantas** [comment]
> have you considered using custom html for this?
> 
> how this would help with us needing custom _new_ strings which are not available in `cstate` yet

For features such as these it's unlikely that I will support them officially (well, at least unlikely for this moment). Not crossing it off the list completely, I mean it's good that people create issues so I know the demand for such things, but seems kind of like an edge case for a status page. Maybe I'm wrong, but I'm trying to provide y'all with a solution that works for now because overriding files isn't fun, but uisng custom HTML will never break your site during updates

Implementing "Experiments" is not hard with custom HTML and you don't _have_ to use i18n strings to do so. Just write "Ongoing experiments here" or whatever other text you want. No biggie.

> I think what would be really helpful as a feature request is being able to amend the strings you provide in the `i18n` folder with own ones. All the layout parts are overlay-able which is very nice, just the localization part seems hard to be customizable. I would not propose to being able to overlay that one similar to the layout case. But amending the already available strings with custom ones seems to be very useful (not just for our case).

Internalization is achieved with a native hugo feature. I think you can 'overlay', add onto the i18n strings list like with the layouts and static folders, but I haven't tried it.

**Comment by gk-tpo** [comment]
Okay, thanks. I'll look into the i18n "overlay" idea and stick to hard-coded text otherwise. I am closing this issue then. Thanks for your help.

**Comment by mistermantas** [comment]
Let me know if it works for you!

**Comment by gk-tpo** [comment]
> Let me know if it works for you!

It actually does, very nice! I just added our three new strings into `i18n/en.yaml` in the repo root dir (where we have the `layouts` folder with the overlays we need) and those strings get picked up if needed.

I am re-opening this ticket in case you want to update the `cstate` documentation, so you can track that task that way. Otherwise just close it again. :)
