### ISSUE TITLE
Maintenance Issue Type

### ISSUE THREAD

**Issue by Semisol** [cstate/cstate#190]
**Is your feature request related to a problem? Please describe.**
It is just sort of annoying not having maintenance types.

**Describe the solution you'd like**
A maintenance issue type, which would allow you to set:
? means optional
- starting date [Date?]
- ending date [Date?]
- creation date [Date]
- title [String]
- done [Boolean]
- affected [String[]]
- ..other issue meta which would be relevant but I forgot

Not much else. The "dynamic"ness would be sorta hard to implement without JS, so a JS disabled fallback showing the dates only (no timers etc) would be needed.
**Describe alternatives you've considered**
Making a notice + down issue, but that does not still show the full picture.

**Additional context**
Not really.

**Comment by mistermantas** [comment]
notice types are intended to be used for maintenance

**Comment by Semisol** [comment]
> notice types are intended to be used for maintenance

okay, but i want some kind of display on the status of the service and maybe a banner at the top.

**Comment by mistermantas** [comment]
this functionality exists if a maintenance issue (severity notice) is active, as in, not resolved

**Comment by Semisol** [comment]
Oh thanks, I guess we can maybe mark this as resolved. Still, dates would be a useful feature and renaming notice to maintenance leaves out the possibility for other types of notices.

**Comment by mistermantas** [comment]
Personally i don't see a reason to make a feature more narrow, as in, only constraining it to maintenance, plus the word is longer which is a very fair argument when you want to get something up on your page quickly 

Extra dates can be provided inside the content if you so wish. You still must define the start date.

**Comment by Semisol** [comment]
Okay.
