### ISSUE TITLE
Component-specific severity

### ISSUE THREAD

**Issue by Semisol** [cstate/cstate#191]
**Is your feature request related to a problem? Please describe.**
I sorta want to set different component to have different severities depending on the issue.

**Describe the solution you'd like**
Setting a severity for each component and the issue itself (to display at the top)
About #190 you should be able to set maintenance and other types for "maintenance" issues but not the inverse.

**Describe alternatives you've considered**
Making multiple issues

**Additional context**
None

**Comment by mistermantas** [comment]
> I sorta

that's not the kind of hesitation that's to be expected from someone asking for a new feature!

Anyhow, unfortunately you'd have to make multiple issues with each issue having the kind of severity that you want to alert users about. In essence, the status page can only highlight 1 status - either down if there is something that's down, disrupted if anything is disrupted, notice, and all systems ok if there are absolutely no active systems.

This is also a duplicate.

**Comment by mistermantas** [comment]
#47

**Comment by Semisol** [comment]
Okay I guess.
