### ISSUE TITLE
Netlify Build Fails

### ISSUE THREAD

**Issue by Sarveshmrao** [cstate/cstate#201]
**Describe the bug**
I updated from v4 to v5 using #151. 
Now I'm unable to build in netlify. 
This is the error I get. 
![image](https://user-images.githubusercontent.com/49156390/128630787-3eb091b6-9358-40b6-88d3-07568ee997c6.png)

**Expected behavior**
It builds and updates to latest version of cState

**Screenshots**
Error screenshot
![image](https://user-images.githubusercontent.com/49156390/128630802-36ac0f8f-3071-47a1-a3f7-b1b14aeb98ec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: idk :)

**Additional context**
Repo link: https://github.com/sarveshmrao/smr-status
Status Page: https://status.sarveshmrao.in

**Comment by mistermantas** [comment]
You updated to v5.0.4 on the repo but your live site isn't updated yet cuz it can't build on the new ver

The config file isn't indenting these options -

useRelativeTime: false
skipSeconds: false

They should be under Params like other options

Looks like you may be using netlify cms so it may be an issue with that

**Comment by Sarveshmrao** [comment]
Hey! 

Thanks for your reply! 

I was directly editing in GitHub. 

So the issue was not putting the 
```
useRelativeTime: false
skipSeconds: false
``` 
intended inside params just like other options. 

Now it's fixed thank you so much!

**Comment by mistermantas** [comment]
Happy to help
