### ISSUE TITLE
Open-marker can be confused for service disruption

### ISSUE THREAD

**Issue by asdofindia** [cstate/cstate#202]
When a first time person sees a status site (which is often the case when there is a service disruption), they can confuse the X mark that is the open-marker for categories to indicate that the service is facing an issue.
 
![image](https://user-images.githubusercontent.com/945777/130074488-96de5517-159e-433d-86f3-9814d4843886.png)

Even though it is very clearly written that it is "operational", I was confused for a moment because the visual element showed an X mark.

I think a ▲triangle solves this issue.

![image](https://user-images.githubusercontent.com/945777/130074808-ea9416ae-c23a-4832-8dcb-2d0b50216ae4.png)

**Comment by mistermantas** [comment]
The triangles are quite ugly though. I would like to use chavrons but unicode doesn't seem to support those.

**Comment by asdofindia** [comment]
How about ⭘
![image](https://user-images.githubusercontent.com/945777/130222182-ebc750cf-0379-404c-a0e7-2980f31a1f9d.png)

Or ◉
![image](https://user-images.githubusercontent.com/945777/130222568-d89e026d-ba6f-41f4-bf55-cb83f6941bec.png)

Or ⁄
![image](https://user-images.githubusercontent.com/945777/130222970-0e7d3cc6-8f1c-4659-850f-6f4423004e33.png)

Or ×
![image](https://user-images.githubusercontent.com/945777/130223046-3fe4941a-2122-46cc-be54-2736f47a81df.png)

**Comment by mistermantas** [comment]
We're using an x already. The other ones are tragic UX (radio inputs can't be unselected)

**Comment by asdofindia** [comment]
Hmm. This x is smaller and maybe less confusing. But your call.

Would you be okay if I make a PR where this character is configurable?

**Comment by mistermantas** [comment]
i can change it to be smaller but honestly this is such a non issue in my opinion, if it's confusing for a split second so be it - it's worse to have many useless options
