### ISSUE TITLE
Invalid JSON created at https://site.com/issues/index.json

### ISSUE THREAD

**Issue by tbmetcalfe** [cstate/cstate#204]
Issue can be found directly at https://test-status.fatmap.com/issues/index.json
Note the additional comma at the very bottom of the list of incidents which is the last element of the JSON data. The stripped down JSON data looks like this:
`{
  "is": "issues",
  "title": "Issues",
  "baseURL": "https://test-status.fatmap.com",
  "description": "",
  "pages": [ ],
}`

**Comment by afirth** [comment]
thanks @mistermantas! :heart:
