### ISSUE TITLE
Offer graphical badges for the status of specific systems or categories

### ISSUE THREAD

**Issue by pheraph** [cstate/cstate#208]
**Is your feature request related to a problem? Please describe.**
I would like to integrate more specific badges with status information of individual systems or categories into other web.

**Describe the solution you'd like**
A very simple and versatile solution might be to extend #91 and offer status badges for individual services via parameterizable URLs, which would then - without the need for JS on the outputting web page - allow the inclusion of status badges just via HTML code (e.g. `<img src=".../systemname/status.svg">`.

**Describe alternatives you've considered**
A conceivable alternative would be to parse the JSON API. However, this would be overshooting the mark and not in all target environments it is possible to execute client-side JS.

**Additional context**
Hopefully not necessary.

**Comment by mistermantas** [comment]
I think the code for index.svg can be the same (or mostly the same) and be reapplied for other categories just because of how hugo parses things

will get this done soon for v5.1
