### ISSUE TITLE
Allow rss feed per group

### ISSUE THREAD

**Issue by kaystrobach** [cstate/cstate#215]
**Is your feature request related to a problem? Please describe.**

The groups we use are related to target groups.
So it makes sense to create different rss feeds.

Options are:

* per system - supported
* Global - supported 
* Per group of systems - missing

**Describe the solution you'd like**

Auto create rss feeds per group

**Describe alternatives you've considered**

Using an external service to merge rss feeds

**Additional context**

none

**Comment by mistermantas** [comment]
Hi! Systems and global RSS feeds are generated automatically by  Hugo. Category RSS support would be a hack. Categories themselves aren't recognized as a taxonomy by Hugo.

I'm unlikely to add it but I'll think about it

Mantas Vilčinskas

**Comment by kaystrobach** [comment]
would it be possible to add another taxonomie?

maybe it's an option to just add the related groups as taxonomies as well?

**Comment by mistermantas** [comment]
Not that I know of

**Comment by kaystrobach** [comment]
will try. happy to get a hint, if you have any 😄

**Comment by mistermantas** [comment]
Maybe make a separate taxonomy altogether that cpbbles together posts from multiple other systems but these systems would have to probably defined in the config file and you'd have to write some complex templating code for that.

It's probably gonna be a bit hacky.

**Comment by mistermantas** [comment]
Hi, @kaystrobach - have you found a solution for this that works for you?

**Comment by kaystrobach** [comment]
not really, we used the json code to compile for our needs. this is a bit hacky as well. 

But i wonder if that's possble anyway, as we still have that requirement to clean up our codebase.
