### ISSUE TITLE
Rework Gitlab example integration

### ISSUE THREAD

**Issue by kaystrobach** [cstate/cstate#217]
**Is your feature request related to a problem? Please describe.**

We want to review changes in gitlab with review apps

**Describe the solution you'd like**

use gitlab review app button inside the MR

**Describe alternatives you've considered**

there are none 😄 

**Additional context**

I'm currently working on this.
The goal is to have an all in one workflow with preview from the build artifacts.

One thing, which breaks for me right now is the way how the index documents are linked:

they are linked like 'folder/' instead of 'folder/index.html' this breaks with gitlab view from artifacs, as this expects a complete link to a file

Are you interested in this?

**Comment by mistermantas** [comment]
> they are linked like 'folder/' instead of 'folder/index.html' this breaks with gitlab view from artifacs, as this expects a complete link to a file

I see. Yeah I can test a change like this, not sure how suitable it would be to push this to everyone, but I don't think it should break anything for other people.

I have limited experience with gitlab but I think better support for it would be beneficial.

**Comment by kaystrobach** [comment]
I would just extend the .gitlab-ci file for the new features.

If you like, i can also pack this in extra files, which are then included (so the feature can be easily enabled / disabled) 😄

**Comment by mistermantas** [comment]
you can create a PR, sure

**Comment by kaystrobach** [comment]
i'm still experimenting with it.

**Comment by mistermantas** [comment]
@kaystrobach - Hi, have you reached a solution for yourself yet?

**Comment by mistermantas** [comment]
If you're still interested, please let me know and I can re-open the issue and push this upstream.

Happy holidays!

**Comment by kaystrobach** [comment]
Ah yes and we have this solved

**Comment by mistermantas** [comment]
> Ah yes and we have this solved

Nice, how did you fix it? Did you do any changes to `.gitlab-ci.yml`?

https://github.com/cstate/cstate/blob/master/exampleSite/.gitlab-ci.yml
