### ISSUE TITLE
Categories in `affected`

### ISSUE THREAD

**Issue by rocketnateynate** [cstate/cstate#222]
Is it possible to declare a category down in the `affected` section of an issue, and have it mark all systems in that category as affected?  I tried this and can't seem to get it to work and couldn't find any issues or docs referencing it. It could be by design.

**Comment by mistermantas** [comment]
This is not possible by design.

**Comment by rocketnateynate** [comment]
Thanks, I figured that was the case, I assume the supported way is to just tag all impacted services in the issue.
