### ISSUE TITLE
 toml file parsing fails in netlify

### ISSUE THREAD

**Issue by Doezer** [cstate/cstate#230]
**Describe the bug**
Deploying the example project in Netlify creates a parsing error : 

```
4:12:56 PM: Failing build: Failed to parse configuration
4:12:56 PM: Failed during stage 'Reading and parsing configuration files': 
When resolving config file /opt/build/repo/netlify.toml:
Could not parse configuration file
Cannot redefine existing key 'headers,values'.

: exit status 1
```

**Reproduction steps**
1. click on "deploy" button in project readme
2. check deploy results

**Expected behavior**
deployed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 11

**Comment by mistermantas** [comment]
Will investigate thanks for the report!

**Comment by Doezer** [comment]
I found this issue that seems to be related : https://github.com/netlify/build/issues/2290

**Comment by mistermantas** [comment]
this was fixed, you can now use the deploy to netlify button

sorry for the trouble!
