### ISSUE TITLE
How to add Uptime robot to cstate

### ISSUE THREAD

**Issue by ssangyongsports** [cstate/cstate#235]
HI,I read Setting up monitoring, I still don't understand, how to add Uptime robot to
cstate

**Comment by mistermantas** [comment]
cState does not have monitoring built-in at this point in time. It is supposed to be a hub for getting up to date information about downtime and analyzing it. You may use a service such as [Uptime Robot](https://uptimerobot.com/) to track uptime and link to their monitoring tools with [**custom tabs**](https://github.com/mistermantas/cstate/wiki/Customization#tabs).

More options with more effort are discussed in the wiki: https://github.com/cstate/cstate/wiki/Usage#setting-up-monitoring

**Comment by ssangyongsports** [comment]
Hi, but I can't find monitoring link like **https://example.com/monitoring.php** in Upptime robot

**Comment by mistermantas** [comment]
I don't work for uptime robot, I don't know how to share the statistics but basically you can look to any site that has info like that.

**Comment by ssangyongsports** [comment]
Sorry to bother again, any recommendation? Because I can't find any monitoring products and this link?
