### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by kr-tukimi** [cstate/cstate#236]
**Describe the solution you'd like**
A Japanese translation of cstate has been prepared for use in Japanese.

this is my commit:
https://github.com/kr-tukimi/cstate/commit/6758ca707ea99ad5a3a83a58a30b777eaea81683

Thanks for the great project! ✨

**Comment by mistermantas** [comment]
excellent! <3 are you not able to submit a pull request to `dev`?

**Comment by kr-tukimi** [comment]
Sure!
The pull request is #237

**Comment by mistermantas** [comment]
will release soon to main branch
