### ISSUE TITLE
List view "Next" and "Prev" unicode characters not well-supported

### ISSUE THREAD

**Issue by bitfehler** [cstate/cstate#242]
**Describe the bug**
This is sort of a follow-up to #96 - on my up-to-date Arch Linux with quite a few fonts installed, I cannot find a single font that supports the Unicode characters chosen as the icons for "next" (⭢ / U+2B62) and "prev" (⭠ / U+2B60) in the list view. This includes fonts specifically included in the CSS (e.g. Roboto) as well as other fonts I would dare call reasonably high-profile (Fira, Linux Libertine, Ubuntu, ...).

For the purpose of reproduction it is enough to just browse the source code on Github:

**Reproduction steps**
1. Go to https://github.com/cstate/cstate/blob/master/layouts/_default/list.html#L79
2. The "icon" is not shown, instead a fallback character (depending on your system fonts, often an empty square)

**Expected behavior**
The icon should be displayed if a reasonable selection of fonts is available on the system. Specifically, it would probably make sense to pick an icon that is available in all fonts that are specifically included in the CSS.

**Screenshots**
Can be supplied if necessary.

**Desktop (please complete the following information):**
 - Arch Linux
 - Firefox & Chrome

**Additional context**
Just noticed this and thought I'd let you know. If you're open to changing this I am also happy to help look for potential replacements. For example, most of my fonts support ◂ / U+25C2 and ▸ / U+25B8, or the bigger versions ◀ / U+25C0 and ▶ / U+25B6, but I haven't checked this on other systems.

Thanks a lot!

**Comment by mistermantas** [comment]
All praise Macintosh
<img width="531" alt="08-23 at 19 07 23@2x" src="https://user-images.githubusercontent.com/11616378/186207632-99b13179-146b-4229-a695-b066db687e1d.png">

I can probably change it, yes, but I'd like an arrow instead of emoji –  ◀ / U+25C0 and ▶ / U+25Bš – and the other option you supplied isn't actually an arrow but a small triangle – that is ◂ / U+25C2 and ▸ / U+25B8 

<img width="804" alt="08-23 at 19 08 51@2x" src="https://user-images.githubusercontent.com/11616378/186207868-184177e4-0ae8-47ea-857a-24a1c8863381.png">

**Comment by bitfehler** [comment]
Thanks for getting back. The emojis are a Github thing, the characters render normally elsewhere, but they are indeed also just triangles, not real arrows. Finding something suitable is indeed a challenge. Of the triangle-headed arrows, the only one that most of my fonts render is ➝ / U+279D, but: there is no leftwards version of that glyph! :face_with_spiral_eyes: 

It seems the only reliably rendering arrows are the simple arrows (← / U+2190 and → / U+2192), but they are not triangle-headed.

I had no idea this was so difficult :sweat_smile: I'll admit that there is no really equivalent replacement, so if you'd prefer to just close this, that's cool. I think I'll try to get some of the fonts to add these arrows you are currently using, but not sure how well that will work out.

Thanks again for listening, and keep up the nice work!

**Comment by mistermantas** [comment]
> seems the only reliably rendering arrows are the simple arrows (← / U+2190 and → / U+2192), but they are not triangle-headed.

That's fine they look like arrows and that's all I want

**Comment by bitfehler** [comment]
> That's fine they look like arrows and that's all I want

In this case, I opened #243 :slightly_smiling_face:
