### ISSUE TITLE
Right spelling / Translation error

### ISSUE THREAD

**Issue by akopfer** [cstate/cstate#246]
**Describe the bug**
The bug refers to a misspelled word, which can cause errors. This is the word disrupted. This was written dsirupted.

**Reproduction steps**
1. Go to layouts/partials/index/components.html
2. Click on line 134

**Expected behavior**
if statement is not recognized correctly and should work again with the correction

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox

**Additional context**
I noticed at the beginning that the lable disrupted is not translated. This can also be fixed by this I think

**Comment by mistermantas** [comment]
Thanks for the bug report!
