### ISSUE TITLE
Broken "affected" links if baseURL contains non-root path

### ISSUE THREAD

**Issue by zeeZ** [cstate/cstate#251]
**Describe the bug**
Hello, it's me again with an issue similar to #126 😄.
With a config such as baseURL: http://example.com/foo/ links for affected services are broken because they again begin with `/`.

I've narrowed it down to a change introduced in Hugo v0.101.0 (https://github.com/gohugoio/hugo/commit/a5a4422aaeffe0e9df713cf09c73a9cc423a2e1e) that now treats all URLs beginning with a `/` as relative to the root, not to the baseURL.

**Reproduction steps**
1. `cd exampleSite && hugo serve --baseUrl=http://localhost/cstate/ --theme=cstate --themesDir=../.. --verbose`
2. Open `http://localhost:1313/cstate/` in browser
3. Notice broken links up top for affected services (Gateway, Website, API...) both on the main page and from the little tags on individual issues.

I still have the GitLab mirror for the `dev` branch, currently built with Hugo v0.104.3, up at https://kurisuchan.gitlab.io/cstate/ that shows the same behavior

**Context**
cstate: master (8af8ff5df208ca77642f5a119a11301605b1ffc1)
hugo: v0.105.0

**Additional information**
Replacing `/affected/...` with `affected/...` seems to do the trick. I have a branch with those changes at https://github.com/zeeZ/cstate/commit/0727f66268e40fdd60f9891f420a1d0a145aa6ec and could create a PR if wanted, just need a new dev branch. I've tried the change with some older versions down to v0.80.0 and nothing seems to break.

**Comment by mistermantas** [comment]
would changing the behavior to fix it for from 0.101 onwards somehow impact the people that use lower versions?

**Comment by zeeZ** [comment]
With the change in place I tried random versions down to v0.80.0 from end of 2020 and the URLs seemed to still render correctly, so I don't think there should be any impact.

There's no dev branch right now, so I'll point the PR at master for the time being.
