### ISSUE TITLE
Netlify failure to Deploy

### ISSUE THREAD

**Issue by HenryCpr** [cstate/cstate#253]
I'm having problems deploying on Netlify this is the console log 

`7:09:23 PM: build-image version: 4c0c1cadee6a31c9bb8d824514030009c4c05c6a (focal)
7:09:23 PM: build-image tag: v4.15.0
7:09:23 PM: buildbot version: 7f32f5823a1f12cc27aca308d8bb5755d6ed0771
7:09:23 PM: Building without cache
7:09:23 PM: Starting to prepare the repo for build
7:09:23 PM: No cached dependencies found. Cloning fresh repo
7:09:23 PM: git clone https://github.com/HenryCpr/status-page
7:09:24 PM: Preparing Git Reference refs/heads/master
7:09:24 PM: Parsing package.json dependencies
7:09:25 PM: ​Warning: some headers have syntax errors:​Could not parse header number 1:  {"for":["/*"],"values":{"Access-Control-Allow-Origin":"*"}}"for" must be a string not: /*
7:09:25 PM: Section completed: initializing
7:09:25 PM: Starting build script
7:09:25 PM: Installing dependencies
7:09:25 PM: Python version set to 2.7
7:09:26 PM: v16.18.1 is already installed.
7:09:26 PM: Now using node v16.18.1 (npm v8.19.2)
7:09:26 PM: Enabling node corepack
7:09:26 PM: Started restoring cached build plugins
7:09:26 PM: Finished restoring cached build plugins
7:09:26 PM: Attempting ruby version 2.7.2, read from environment
7:09:27 PM: Using ruby version 2.7.2
7:09:27 PM: Using PHP version 8.0
7:09:27 PM: Installing Hugo 0.80.0
7:09:28 PM: Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z
7:09:28 PM: Started restoring cached go cache
7:09:28 PM: Finished restoring cached go cache
7:09:29 PM: Installing Go version 1.19.3 (requested 1.19.x)
7:09:34 PM: unset GOOS;
7:09:34 PM: unset GOARCH;
7:09:34 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.19.3.linux.amd64';
7:09:34 PM: export PATH="/opt/buildhome/.gimme/versions/go1.19.3.linux.amd64/bin:${PATH}";
7:09:34 PM: go version >&2;
7:09:34 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.19.3.linux.amd64.env"
7:09:34 PM: go version go1.19.3 linux/amd64
7:09:34 PM: Detected 1 framework(s)
7:09:34 PM: null at version null
7:09:34 PM: Installing missing commands
7:09:34 PM: Verify run directory
7:09:35 PM: ​
7:09:35 PM: ────────────────────────────────────────────────────────────────
7:09:35 PM:   Netlify Build                                                 
7:09:35 PM: ────────────────────────────────────────────────────────────────
7:09:35 PM: ​
7:09:35 PM: ❯ Version
7:09:36 PM: Creating deploy upload records
7:09:35 PM:   @netlify/build 28.4.4
7:09:35 PM: ​
7:09:35 PM: ❯ Flags
7:09:36 PM:   baseRelDir: true
7:09:36 PM:   buildId: 6388a079ec1d29169d4eb80b
7:09:36 PM:   deployId: 6388a079ec1d29169d4eb80d
7:09:36 PM: ​
7:09:36 PM: ❯ Current directory
7:09:36 PM:   /opt/build/repo
7:09:36 PM: ​
7:09:36 PM: ❯ Config file
7:09:36 PM: Starting post processing
7:09:36 PM:   /opt/build/repo/netlify.toml
7:09:36 PM: ​
7:09:36 PM: ❯ Context
7:09:36 PM: Post processing - HTML
7:09:36 PM:   production
7:09:36 PM: ​
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM:   1. build.command from netlify.toml                            
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM: ​
7:09:36 PM: Post processing - header rules
7:09:36 PM: $ hugo
7:09:36 PM: Start building sites …
7:09:36 PM:                    | EN
7:09:36 PM: -------------------+-----
7:09:37 PM: Starting post processing
7:09:36 PM:   Pages            | 39
7:09:36 PM:   Paginator pages  |  0
7:09:36 PM:   Non-page files   |  0
7:09:37 PM: Post processing - HTML
7:09:36 PM:   Static files     | 10
7:09:36 PM:   Processed images |  0
7:09:36 PM:   Aliases          |  6
7:09:36 PM:   Sitemaps         |  1
7:09:36 PM:   Cleaned          |  0
7:09:36 PM: Total in 52 ms
7:09:37 PM: Post processing - header rules
7:09:36 PM: ​
7:09:36 PM: Warning: some headers have syntax errors:
7:09:36 PM: ​
7:09:36 PM: Could not parse header number 1:
7:09:37 PM: Starting post processing
7:09:36 PM:   {"for":["/*"],"values":{"Access-Control-Allow-Origin":"*"}}
7:09:36 PM: "for" must be a string not: /*​
7:09:36 PM: (build.command completed in 99ms)
7:09:36 PM: ​
7:09:37 PM: Post processing - HTML
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM:   2. Functions bundling                                         
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM: ​
7:09:36 PM: The Netlify Functions setting targets a non-existing directory: functions
7:09:37 PM: Post processing - header rules
7:09:36 PM: ​
7:09:36 PM: (Functions bundling completed in 1ms)
7:09:36 PM: ​
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM:   3. Deploy site                                                
7:09:38 PM: Starting post processing
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM: ​
7:09:36 PM: Starting to deploy site from 'public'
7:09:38 PM: Post processing - HTML
7:09:36 PM: Creating deploy tree 
7:09:36 PM: 1 new files to upload
7:09:36 PM: 0 new functions to upload
7:09:36 PM: Section completed: deploying
7:09:36 PM: Site deploy was successfully initiated
7:09:38 PM: Post processing - header rules
7:09:36 PM: ​
7:09:36 PM: (Deploy site completed in 314ms)
7:09:36 PM: ​
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:38 PM: Starting post processing
7:09:36 PM:   Netlify Build Complete                                        
7:09:36 PM: ────────────────────────────────────────────────────────────────
7:09:36 PM: ​
7:09:38 PM: Post processing - HTML
7:09:36 PM: (Netlify Build completed in 481ms)
7:09:36 PM: Caching artifacts
7:09:36 PM: Started saving build plugins
7:09:36 PM: Finished saving build plugins
7:09:36 PM: Started saving pip cache
7:09:36 PM: Finished saving pip cache
7:09:39 PM: Post processing - header rules
7:09:36 PM: Started saving emacs cask dependencies
7:09:36 PM: Finished saving emacs cask dependencies
7:09:36 PM: Started saving maven dependencies
7:09:36 PM: Finished saving maven dependencies
7:09:36 PM: Started saving boot dependencies
7:09:36 PM: Finished saving boot dependencies
7:09:36 PM: Started saving rust rustup cache
7:09:36 PM: Finished saving rust rustup cache
7:09:36 PM: Started saving go dependencies
7:09:36 PM: Finished saving go dependencies
7:09:38 PM: Build script success
7:09:38 PM: Section completed: building
7:09:39 PM: Uploading Cache of size 80.6MB
7:09:39 PM: Section completed: cleanup
7:09:39 PM: Finished processing build request in 16.077926047s`

This is the Error I get 

`We couldn’t deploy your site. Check out our Build docs for tips on troubleshooting your build, and if that doesn’t help, please review our Support Guide on extended debugging before asking us for debugging advice`

**Comment by mistermantas** [comment]
where did you set up this site? did you press the Deploy to Netlify button and not edit anything? 

` 7:09:36 PM: Could not parse header number 1: 7:09:37 PM: Starting post processing 7:09:36 PM: {"for":["/*"],"values":{"Access-Control-Allow-Origin":"*"}} 7:09:36 PM: "for" must be a string not: /*​ 7:09:36 PM: (build.command completed in 99ms`

this is the only thing in the build process that could error out, but it looks like the build succeeded..? so i’m not really sure if it’s your build settings like with the post processing or if it’s the CORS header warning

**Comment by HenryCpr** [comment]
I just clicked on the Deploy to netlify nothing else.

**Comment by mistermantas** [comment]
go to netlify.toml and scroll down to `[[headers]]`, remove the `[]` surrounding `/*` so it's `= "/*"` instead of `= ["/*"]`

**Comment by mistermantas** [comment]
https://github.com/cstate/cstate/commit/db474e411e96945ce905504fb0a3c97477fcd305
