### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Summit-Productions** [cstate/cstate#255]
Since there wasn't a question one. How do I make it so there is a maintenance mode for it?

**Comment by mistermantas** [comment]
the site does not have a maintenance mode - it can't be closed off like a shopify store

if you want the status to change from "All Systems Operational" to "Maintenance Soon" or something like that, please create a new issue file and set the **severity** to **notice**

more info can be found on the wiki

**Comment by Summit-Productions** [comment]
How do I do that?

**Comment by mistermantas** [comment]
if you want the status to change from "All Systems Operational" to show the maintenance post, please create a new issue file and set the severity to notice

https://github.com/cstate/cstate/wiki/Usage#creating-incidents-method-1
