### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by Summit-Productions** [cstate/cstate#256]
Hi there,

How would I make cState go with a Discord Embed so when a certain part is down it edits the embed to show that certain sector is down?

**Comment by mistermantas** [comment]
cstate does not have webhooks built in

https://docs.netlify.com/configure-builds/build-hooks/

you can maybe use your hosting provider to send alerts for when the status page changes

it is possible to also write a lambda func for this purpose

i am aware cstate lacks alert, something worth addressing in the future
