### ISSUE TITLE
Category / System Page Anchor Links

### ISSUE THREAD

**Issue by mmadson** [cstate/cstate#257]
**Is your feature request related to a problem? Please describe.**
When there are multiple categories on a single page, each with multiple systems, the page becomes quite long to scroll and find exactly which service you are looking for. If you want to quickly inform a stakeholder about your system's status on a such a cluttered page, asking them to CTRL+F for your service name isn't a great experience.

**Describe the solution you'd like**
It'd be much nicer if you could provide them a link with an anchor that would automatically scroll them to the category / system on the page so they can quickly see the particular system's current status. 

**Describe alternatives you've considered**
The affected page could also be used for this purpose if the affected page also conveyed the current status of the system as well as the system's description; however if the system has never had an issue the default message is a bit misleading which can cause confusion.

**Comment by mistermantas** [comment]
good idea!

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by mistermantas** [comment]
this will be added in v6! :)
