### ISSUE TITLE
Inabaility to view webpages with "View Live"

### ISSUE THREAD

**Issue by Lexian-droid** [cstate/cstate#262]
**Describe the bug**
In the "Pages" tab in the admin panel, It is not possible to view the pages you create, when you click on a page, and select "View Live" It will instead give the base URL without the page in the URL, making it not possible to find links to pages if you try to create custom ones, say for Information.

**Reproduction steps**
1. Go to your status site
2. Log in to the panel
3. Go to "Pages"
4. Create or select an already existing page
5. Select "View Live"
You'll notice the page doesn't load and the URL is just the base URL.

**Expected behavior**
It is expected that the site loads the page you wish to view live, and reflect that in the URL.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 110.0.1

**Smartphone (please complete the following information):**
- No relation, Was never used on a phone.

**Additional context**
I tried things like, saving as a draft, removing special characters, waiting for a few hours, but none of it seems to work.
Also, I am using Netlify, so that it can a backup if my main server goes down. So I'm using the Netlify CMS.

**Comment by mistermantas** [comment]
Apologies for taking this long to respond.

Yes, I don't believe netlify cms automatically appends the page url to the view live button and I had manually defined it to go to the baseurl, so the homepage.

Perhaps worth taking a look at to improve UX whenever I have more free time to do open source
