### ISSUE TITLE
Code blocks are not contained

### ISSUE THREAD

**Issue by JacksonChen666** [cstate/cstate#263]
**Describe the bug**
Code blocks, when very long, are allowed to overflow outside of the `contain` class.

**Reproduction steps**
1. Create a code block with a really really long line, so long that the text is larger than the container (maybe copy this line?)
2. Look at code block

**Expected behavior**
The code block does not overflow outside of the box

**Screenshots**
<img width="1920" alt="A cState status page. The code block goes outside of where the usual content is." src="https://user-images.githubusercontent.com/50755746/231577382-061de0ac-c3f1-447f-96b4-c6767bfc6ccd.png">
<img width="1920" alt="A cState status page. The code block is not overflowing, and is scrolled a little bit." src="https://user-images.githubusercontent.com/50755746/231577408-89390277-62c2-428a-a10d-035eef3dbf63.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser LibreWolf (Firefox fork)
 - Version 111.0.1-1

**Additional context**
The solution was included in the picture, and also below:
```css
pre {
    overflow-x: scroll;
}
```

Make sure to test it a variety of cases. (I also might make a PR myself to fix this issue since you know, I already got the solution right above)

**Comment by mistermantas** [comment]
> Make sure to test it a variety of cases. (I also might make a PR myself to fix this issue since you know, I already got the solution right above)

Thanks for creating an issue. Yes, you have the right solution. Well, sort of, this should be limited to the container box for Markdown text, like `.markdown pre` or something else. But pre is not used anywhere else by default.

If you have the time, feel free to make a PR to merge it into **dev** (not sure if the branch exists still, but it should).

**Comment by mistermantas** [comment]
I 7

**Comment by mistermantas** [comment]
> > I 7
> 
> ?

that’s strange, I must have accidentally replied.  This will be in the newest cstate update soon, just cleaning up the issues before I release it.
