### ISSUE TITLE
`resolvedAfter` wording is always "of downtime" even when issue `severity` is marked as `distrupted`

### ISSUE THREAD

**Issue by nbarton915** [cstate/cstate#264]
**Describe the bug**
When viewing past issues that have been resolved, the wording is always `Resolved after <x time> of downtime` even if an issue is marked as `disrupted` for it's severity.

**Pre-Reqs**
- Ensure `disableIncidentHistory: false`
- Ensure at least one incident has been created with `severity: disrupted`

**Reproduction steps**
1. Scroll to `Incidents` tab at the bottom of the page
2. Assert defined incident summary appears. Success :heavy_check_mark: 
3. Assert defined incident summary describes the appropriate severity level (disrupted). Assertion Failed :x: 
5. Click on incident summary
6. Assert incident details page is shown. Success :heavy_check_mark: 
7. Assert incident details page describes the appropriate severity level (disrupted). Assertion Failed :x: 

**Expected behavior**
I am very pleased to find a project that is simple to set up and simple to understand. I like the use of `Operational`, `Notice`, `Disrupted`, and `Down` (or downtime). The expected behavior in this case is to describe a past issue as the severity level set in the incident markdown (either `notice` or `disrupted`).

For example: If I had an incident that lasted 9 minutes until resolved and had the `disrupted` severity level, I would expect the message to be: `Resolved after 9m of disruption.` both in the incident summary and the incident details.  

**Screenshots**
The following past incident had a severity of `disrupted` because no components ever were `down.` However, it appears that the severity was `down` because the text says: `Resolved after 4m of downtime`
 
![image](https://user-images.githubusercontent.com/19895285/231605267-42becd65-253e-4ffa-a889-c80647aef29e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox, Chrome, Chromium
 - Version: cstate v5.5.1

**Additional context**
The words `down` and `downtime` are filled with weight in our organization. We only use them if they are factually true. If an incident did not result in downtime then it would be nice to have past incidents represent that.

Thanks for all of your hard work. We really enjoy this project.

**Comment by mistermantas** [comment]
Thanks for your issue.

Definitely an oversight on my part.

I think simply removing the word "downtime" (unless it is actually downtime) would fix this issue, e.g. _Resolved after 4m_

When it comes to editing the UI text, though, I am hesitant to do it because there's people using translations and I'm not confident enough to call myself a polyglot yet.

So, definitely doable for the english (and lithuanian) versions right off the bat, will need to look into how to not break the grammatical/lexical structure in other languages

you should be able to override the language files in your local install of the status page, by the way.

**Comment by nbarton915** [comment]
Thanks for the suggestion. I'll take a look to see what options I have with our installation method being github pages. I'm sure that I can fork cstate, but I would prefer to keep the link to your project in case there are other changes that come down the pipe. I'll give it some thought and proceed based on your feedback.

I'll also keep watching this item in case there are any updates.

Thanks!

**Comment by nbarton915** [comment]
Like you said, only showing the word `downtime` if the severity is down seems like the way to go. I have a commit in a branch [here](https://github.com/cstate/cstate/compare/master...nbarton915:cstate:severity-aware-resolution) that appears to accomplish that without messing with the grammar.

I'm going to do some more testing, but if you are open to it, I'd be happy to create a PR. If so, would you like the PR into master or dev?

**Comment by mistermantas** [comment]
PRs are sent to dev
