### ISSUE TITLE
typo in translation of var highestlevel status for categories 

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#266]
**Describe the bug**
the highestlevel status of a category on the index site does not respect translations in case of "disrupted". it always shows the string "disrupted" - independet of the defined wording in i18. 

**Reproduction steps**
create an incident with severity "disrupted" and change the wording in i18n.

**Expected behavior**
see the wording

**Additional context**
There is a typo in themes/cstate/partials/index/components.html, line 134
`if (highlestLevelStatus === 'dsirupted') { highlestLevelStatusReadable = '{{ T "thisIsDisrupted" }}' } `
"disrupted" is mispelled. therefore the translation won't be applied.

please fix :)

**Comment by mistermantas** [comment]
If you have the time, you can make a PR and I'll push it faster.
