### ISSUE TITLE
Feature to exclude some incidents from beeing pined in the anouncements

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#267]
**Is your feature request related to a problem? Please describe.**
Simetimes you don't want to have all incidents being pined in the announcements. Exspecially if you have a large service portfolio and lots of Maintainance notices oder smaller issues etc.

**Describe the solution you'd like**
-> A feature to exclude an incident from being pinned.
Add filter to exclude incidents from being pinned in the announcements, if they explicitly set the Param "pin: false"
default: unresolved incidents will be pinned. 

**Side benefit: ** the Param "pin: false" will be respected in both: incidents and informationals

**Comment by mistermantas** [comment]
agree with this idea
