### ISSUE TITLE
individuel Pages for all systems - not only affected ones

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#269]
**Is your feature request related to a problem? Please describe.**
at the moment: cstate/hugo only creates pages for systems, which are currently affected by an incident. 
clicking on a system's name (without incidents) on the index page forwards to the 404.html-page, with is showing a vague message like "doc not found OR no incident recorded OR url maybe wrong" (it's not the fault of the 404-page: he/she/it can't know for sure)
It would be more user-friendly, if more precise information could be displayed.

**Describe the solution you'd like**
rendering/creating page for _all_ systems would be a solution for this problem. 
`_default/lists.html` seems to be already prepared for this usecase: Lines 59ff formulate an if-clause to include the `calmBeforeTheStorm`-message. (however, as the pages for systems currently will only be rendered, if there are incidents, the `calmBeforeTheStorm` is never displayed) :(

**Describe alternatives you've considered**
i tried to create inndividual pages per system in a folder `content/affected/`. this kind of works. however, this would be some form of duplicate data storage, as the systems names are already defined in `config.yml`. (Furthermore, I wasn't able to display die incidents/issues belonging to the system on it's `content/affected/`-Page. -- if fixable, this might be an alternativ, though)

**Comment by mistermantas** [comment]
This is an issue but..

this issue goes away when you create the first issue. So, in other words, this issue is not persistent. What's your use case that you have many empty categories/systems?

**Comment by MirMiz** [comment]
I want to show the user the extended system's description mentioned in #270 . however, if the site is not rendert, the extended description is not shown. 
in the description we placed additional link to tickettools, selfservice and a small component intro.

**Comment by MirMiz** [comment]
a possible - but a little bit tedious (if not done by python ;)) - **solution** without changing cstate looks like this: 
maybe you could add this to the Wiki, @mistermantas 

create for each system a folder: 
`content/affected/SYSTEMSNAME` and place a `_index.md` file in there (note the `_`) with the content 
```
---
title: Title of the system
---
```

the SYSTEMSNAME needs to exaclty match the URL, which is shown in the components list on the main page. just copy it from there.
(if you want to create it yourself: it is generated from systems-array in `config.yml` like this: `$system.title | urlize`, so the url-safe version of the name. i.e. Spaces and most other special chars get replaced by '-'. However, '+' and '_' won't be replaced)

------------

**Example:** 
`config.yml`: 
```  systems:
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and video. It is reliant on our CDN.
      category: Uncategorized
```

WebUI: 
![grafik](https://user-images.githubusercontent.com/14907823/233868506-6d36f4bb-413c-4bb9-b353-217a9b3fba34.png)
-> `affected/media-proxy/` (note: ' ' -> '-')

Therefore: 
create a folder `affected/media-proxy/` and place a file `_index.md` in there with the following content: 
```
---
title: Media Proxy
---
```

**Comment by mistermantas** [comment]
This is at least partially fixed in v6 using API lookup, so you don't get a 404 page.
