### ISSUE TITLE
extended system description on affected-page (with markdown support)

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#270]
**Is your feature request related to a problem? Please describe.**
The systems are defined as array in `config.yml`. the description-Attribute allows for some plaintext - markdown won't be evaluated, however.
Use Case: Displaying the systems status is nice. You can privide additional benefit for the user, by referencing the Link to the documentation and/or a link to issue a ticket for this system. and maybe some lines of system description. 
cstate currently allows for only one additional link and a short plaintext description 

**Describe the solution you'd like**
it would be helpful, if the description on the "affected"-pages would allow for markdown. (and thus links)
You could seperate the "description" field in `config.yml` into `tooltip` (plaintext) and `description` (markdown).

**Describe alternatives you've considered**
I used cstate additional link in `config.yml` to point to an additinal page I created for each system. 
this way, however, I have two pages per system: 
1. the cstate-incident-page for the system (by clicking on the systems name)
2. my additional docu-and-tickettool-link-page (by clicking on the link-icon)
That's not that neat and userfriendly as having only one page :/

**Additional context**
Some Mockup: (HTML oder Markdown not evaluatet, however)
![grafik](https://user-images.githubusercontent.com/14907823/233494656-3662016b-9aa6-47d4-9c5f-d74b6ebdfc2f.png)

**Comment by MirMiz** [comment]
alternatifly to `| safeHTML` you could use `| markdownify` if you want to stick in Markdown rather then HTML for user content

**Comment by mistermantas** [comment]
added in v6 with markdown support to descriptions and markdown support for  longer descriptions using /content/


![12-24 at 17 33 17@2x](https://github.com/user-attachments/assets/dd05fc5f-5b63-42d3-8f91-d2f81d688e45)
