### ISSUE TITLE
use cstate colors instead of "ok"/"warning"-color for Incident severities

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#275]
**Is your feature request related to a problem? Please describe.**
the incident history on the Main page shows the status of the incident always in red color -- indepentend of the incident's serverity
the red color used, is the "error" color.

**Describe the solution you'd like**
1. it would be nice to indicate the Severity not only by icon, but also by the severity's color chosen in `config.yml` (and used in the component list above as well)
2. the three icons "■, ▲, ◆" are nice. They lack an explanation, though. Therefore, writing the translation of the serverity next to them would be helpful for the user.

**Comment by mistermantas** [comment]
This'll be fully added in v6. Thank you!
