### ISSUE TITLE
Option to deactive the Netlify-Admin-Pages

### ISSUE THREAD

**Issue by MirMiz** [cstate/cstate#277]
**Is your feature request related to a problem? Please describe.**
When you're building your cstate-Page without a CMS or Netlify, you don't need the netlify-admin-page. 
However it still will be rendered and a path `<yourdomain.com>/admin/` will be accessible. 

**Describe the solution you'd like**
create a flag in `config.yml` to deactive the creation of admin/. 

**Describe alternatives you've considered**
- deleting `theme/cstate/static/admin/` solves this issue. however, you messed with cstates theme/core and can't update that easily anymore. 
- Creating a folder `static/admin/` in your site (outside of theme/cstate/) with two empty files `config.yml` und `index.html`: -> only a blank page will be delivered. However the path `<yourdomain.com>/admin/` is still accessable. 
you can forward to the 404.html-page in this case, though, by placing a `<meta http-equiv="refresh" content="0; url=/404.html"/" />` in your `static/admin/index.html` alone

**Additional context**

**Comment by mistermantas** [comment]
Apologies for the long waiting time.

I don't see the utility in disabling an optional feature which does not interfere with the site. It's also not possible from config.yml
