### ISSUE TITLE
Resolved after 0 minutes should just be resolved

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#28]

**Comment by logichub** [comment]
I have followed the following instructions:

1. Download the contents of the `exampleSite` directory in this repository. This will be your site guts, which will hold the content and configuration for the status page.
2. Create a `themes` folder and navigate to it on the command line.

```bash
mkdir themes; cd themes;
```

3. Now simply add a Git submodule pointing to this repository, like so:

```bash
git submodule add https://github.com/cstate/cstate
```

4. Set up cState for your liking. It is now ready to be used in production.

I have made changes in the local repo and tested it. What's next?

**Comment by mistermantas** [comment]
> I have made changes in the local repo and tested it. What's next?

Make a pull request.

**Comment by mistermantas** [comment]
I checked the repo, these are not the changes that needed to be made. This is supposed to be a somewhat complex Hugo if statement made in `index.html`.

**Comment by logichub** [comment]
I made following changes in the `cstate\layouts\issues\issue.html` file:

```go
    <span class="ok">

      {{ $t := (time .Params.ResolvedWhen) }}
      {{ $timeDiff := (sub $t.Unix .Date.Unix) }}
      {{ $diffInMin := (div $timeDiff 60) }}
        
      {{ if lt $timeDiff 60 }}
            ✓ Resolved
      {{ else }}
            ✓ Resolved after
            {{ if gt $timeDiff 3600 }}
                {{ $minutesForCalc := (mod $diffInMin 60) }}

                {{ div (sub $diffInMin $minutesForCalc) 60 }}h
                {{ $minutesForCalc }}m of downtime
            {{ else }}
                {{ $secsForCalc := (mod $timeDiff 60) }}

            {{ div (sub $timeDiff $secsForCalc) 60 }}m
            <!-- {{ $secsForCalc }}s --> of downtime
          {{ end }}
      {{ end }}
    </span>
```

Then I created 2 more issues in the `content\issues` folder where incident time is less than a minute e.g.

**Incident and resolution time is same i.e. 0 second**

> title: Test Issues
> date: 2018-09-25 00:00:00
> resolved: true
> resolvedWhen: 2018-09-25 00:00:00

![image](https://user-images.githubusercontent.com/6245858/46311619-44a5e580-c5dc-11e8-9cb4-c42032bd6421.png)
<hr>

**Incident and resolution time is less than a minute i.e. 59 seconds**

> title: Test 2 Issues
> date: 2018-10-01 01:15:00
> resolved: true
> resolvedWhen: 2018-10-01 01:15:59

![image](https://user-images.githubusercontent.com/6245858/46311576-1cb68200-c5dc-11e8-9b1c-77757ba2bf4a.png)
<hr>

The old incidents are showing hours and/or minutes as usual.

**Incident and resolution time is more than a minute but less than an hour i.e. 27 minutes**

> title: US East Connection Issues
> date: 2018-05-25 04:13:00
> resolved: true
> resolvedWhen: 2018-05-25 04:40:00

![image](https://user-images.githubusercontent.com/6245858/46311666-630be100-c5dc-11e8-9ec3-15859bc1a9b8.png)
<hr>

**Incident and resolution time is more than an hour i.e. 1 hour 36 minutes**

> title: Unavailable Guilds & Connection Issues
> date: 2018-04-13 15:54:00
> resolved: true
> resolvedWhen: 2018-04-13 17:30:00

![image](https://user-images.githubusercontent.com/6245858/46311688-71f29380-c5dc-11e8-8207-01efbbf6c55e.png)
<hr>

However, my changes are not visible in the forked repo. I am not sure how can I do that.

**Comment by logichub** [comment]
Let me try it. :)

**Comment by mistermantas** [comment]
Having issues? :)

**Comment by logichub** [comment]
Didn't try yet. Been busy in other tasks. Will try to do it later tonight. :)

**Comment by logichub** [comment]
Tried again: https://github.com/cstate/cstate/pull/30

**Comment by mistermantas** [comment]
Alright, moving discussion to there.
