### ISSUE TITLE
Long words in headers may cause overflow and horizontal scrolling

### ISSUE THREAD

**Issue by JacksonChen666** [cstate/cstate#285]
**Describe the bug**
Long words in headers may cause overflow and horizontal scrolling

**Reproduction steps**
1. Go to [my status page](https://status.jacksonchen666.com/issues/2023-10-07-rebooting-the-imac-to-do-some-stuff/#end-2023-10-07t2343040200-postmortem)
2. Resize window to simulate a small viewport
3. See overflow

**Expected behavior**
The text does wrap, not causing horizontal scrolling.

**Screenshots**
Simulated viewport (iPhone SE) in Firefox

<img src="https://github.com/cstate/cstate/assets/50755746/3b6446b3-080a-4605-8bf1-05f4f5fe6f06" height="500" alt="A cState post page with header overflowing the screen.">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: LibreWolf (Firefox fork)
 - Version 118.0.1-1

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: /e/OS
 - Browser: Firefox
 - Version: 118.1.0

**Additional context**

**Comment by sumitrajkumar** [comment]
can you assign me this issue?

**Comment by mistermantas** [comment]
> can you assign me this issue?

You can make a pr and I will merge it

**Comment by Sinu00** [comment]
is this still open?
