### ISSUE TITLE
Enable date-based archiving/hiding of history

### ISSUE THREAD

**Issue by kaihoffman** [cstate/cstate#286]
**Is your feature request related to a problem? Please describe.**

If history is set to visible, it is viewable either by month/year or paginated. This goes as far back as the updates go, which may contain older, immature/development-era issues that make the incident history look worse than it is.

**Describe the solution you'd like**

An option to set a `numMonths` or similar from a date of incident to _not_ display an incident in the history. This could therefore show only e.g. the last year of incidents for a cleaner look.

**Comment by mistermantas** [comment]
frankly this is hard to achieve because you need (a) to rebuild the site for changes to take effect, (b) incident history could just be hidden under a link.

i see the point though. I would accept a PR

**Comment by mistermantas** [comment]
I've opted for option b - incident history on the **homepage** is now truncated by default to option you set it as. There is now a separate **archive page** to view everything in one and it **too can have issues hidden after x years** with a new config update.
