### ISSUE TITLE
count in days/years after 24h

### ISSUE THREAD

**Issue by anarcat** [cstate/cstate#287]
Hi!

**Is your feature request related to a problem? Please describe.**
We have some long running outages, sometimes more than a day. An example of a catastrophic, week-long outage is this:

https://status.torproject.org/issues/2023-11-08-tor-weather-outage/

That says: "Resolved after 300h 5m of downtime". Now people strong in arithmetic will of course figure out that this is a little over a week and somewhat under two.

**Describe the solution you'd like**

Once we cross the 24h threshold, we should display intervals with days. For example, "300h 5m" should display as "12 days,10h 5m" here.

I guess that once you get past the 365 days mark, you might want to count in years too, but i am not sure anyone will reach that threshold. 

But considering we actually use cstate to report on long-running "experiments" as well, that might actually really happen too! That's a local divergence from cstate that i'd like us to contribute back though, see [our internal issue about this for more details](https://gitlab.torproject.org/tpo/tpa/status-site/-/issues/37) and [this component](https://status.torproject.org/affected/network-experiments/) for an example. Update: opened #288 to discuss this.

**Describe alternatives you've considered**
I've long considered just not filing this bug and accepting the status quo, but I figured I might not be the only one finding this odd. :)

**Additional context**

Here's a screenshot of the outage report:

![Screen shot of the incident sayind "Tor Weather data loss October 27, 2023 at 6:23 AM UTC weather.torproject.org Resolved after 300h 5m of downtime"](https://github.com/cstate/cstate/assets/796623/9b25c222-5220-469e-a07f-bb87c1064091)

**Comment by mistermantas** [comment]
Yep, this should be fixed, I'd accept a PR for this. Unfortunately I don't quite have the motivation to go through everything on a timely basis though, it is quite hard to find the motivation to keep working on this project.

**Comment by anarcat** [comment]
Understood. I might take a shot at this, so any idea you have from the top of your head on where to start would be appreciated!

**Comment by mistermantas** [comment]
> Understood. I might take a shot at this, so any idea you have from the top of your head on where to start would be appreciated!

hugo has Math operations which are used in other parts of the code – you could try starting from that.

**Comment by mistermantas** [comment]
Thanks for using cState. This will be fixed in v6 along with other similar issues. I'm closing this for now.
