### ISSUE TITLE
Ukrainian Language

### ISSUE THREAD

**Issue by HighError** [cstate/cstate#290]
A Ukrainian translation of cstate.

https://github.com/HighError/cstate/commit/d26e7077238aa767c8ef6f2ef2a0cadd9d5804ef
https://github.com/HighError/cstate/commit/795344a6cc76c58146d99748f1d2421e3087a464

**Comment by mistermantas** [comment]
Thanks so much for sharing!

could you please make a Pull Request so I can merge it and you get the credit in the git history?

**Comment by HighError** [comment]
@mistermantas into master? I don't see dev branch/
