### ISSUE TITLE
Expose pinned issue(s) in index.json

### ISSUE THREAD

**Issue by dumbmoron** [cstate/cstate#295]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to programatically access pinned informational issues via the generated `index.json` page.

**Describe the solution you'd like**
What I would like to do is add another entry to the index.json output, which would be a global array (as in one array, not for each 'system') of currently open, pinned issues , listed similarly to `unresolvedIssues` for each system in `systems`. I'm planning on making a pull request for this if there are no objections to this feature request -- please let me know if there's something I'm missing or a reason why this shouldn't be implemented.

**Describe alternatives you've considered**
My usecase is that I have a status page which has a lot of automated issues, but also some manual issues which are marked "informational" and pinned for visibility. I would like to access this information from other services programatically, but there's no way to do that except for scraping the generated HTML pages.

**Comment by mistermantas** [comment]
> I'm planning on making a pull request for this if there are no objections to this feature request -- please let me know if there's something I'm missing or a reason why this shouldn't be implemented.

Sounds great. Please make a PR and I'll merge it!
