### ISSUE TITLE
Header to all pages

### ISSUE THREAD

**Issue by jouniso** [cstate/cstate#312]
It's a bit strange that header is only added to front page and not to sub-pages ie. issues or affected systems.
It would be nice to have common look for the page top for all pages. 

It could be as an option so old systems would not be affected.

**Comment by mistermantas** [comment]
that's how status pages look

home: https://status.openai.com/

page: https://status.openai.com/incidents/ssg8fh7sfyz3

![02-21 at 14 33 21@2x](https://github.com/cstate/cstate/assets/11616378/e333188d-09ff-4ce7-aa8a-2e15e7eb41c9)

![02-21 at 14 33 28@2x](https://github.com/cstate/cstate/assets/11616378/52f7ad7b-f1d7-4f5e-9934-8d49caac606b)

**Comment by jouniso** [comment]
> that's how status pages look

No shit, Sherlock – maybe that was why I asked for the improvement? 🤦

**Comment by mistermantas** [comment]
> > that's how status pages look
> 
> No shit, Sherlock – maybe that was why I asked for the improvement? 🤦

I was explaining that it is not strange compared to mainstream status pages. I have no intentions to change the UI though, you can do so yourself for your instance of cstate :)
