### ISSUE TITLE
Git Gateway Error: Please ask your site administrator to reissue the Git Gateway token.

### ISSUE THREAD

**Issue by charlie-jay2** [cstate/cstate#313]
Hi, on my Netlify site. It is https://www.status.flexagroup.co.uk and when I try using the admin panel I get this:

Git Gateway Error: Please ask your site administrator to reissue the Git Gateway token.

**Comment by mistermantas** [comment]
I'm sorry, I can't help with Git Gateway issues and I am guessing your Netlify/Git Gateway setup is incorrect in some sort of way or you needed a refresh.
