### ISSUE TITLE
example site outdated

### ISSUE THREAD

**Issue by FlexaGroup** [cstate/cstate#315]
I have resolved an incident, but it doesn't hide and go to the history. It isn't pinned or anything.

**Comment by mistermantas** [comment]
please send your site source code and a live link, thanks!

**Comment by FlexaGroup** [comment]
**Describe the bug**

I have resolved an incident, but it doesn't hide and go to the history. It isn't pinned or anything. Here is the site: https://status.flexagroup.co.uk

**Reproduction steps**
Steps to reproduce the behavior:
1. Go to https://status.flexagroup.co.uk/admin
2. Click on Incidents
3. Scroll down to Active Incident
4. Click resolved on incident
5. Let it send to netlify and upload to site
6. Doesn't vanish and go to history
7. See error

**Expected behavior**
It is meant to get rid of the incident and show it in the history not on the page.

**Screenshots**
![image](https://github.com/cstate/cstate/assets/162819959/107db55d-806c-4ed4-8aae-2f144af4dfc6)
![image](https://github.com/cstate/cstate/assets/162819959/704e19b1-3376-4516-af25-212a563bfee9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Windows 11

**Additional context**
N/A

**Comment by mistermantas** [comment]
you need to update your cstate version, this seems like an old bug

**Comment by FlexaGroup** [comment]
May I ask, how do I update the version?

**Comment by mistermantas** [comment]
https://github.com/cstate/cstate/blob/master/README.md#updating-

you'll need to download the repo locally, read above

**Comment by FlexaGroup** [comment]
Thank you.

**Comment by FlexaGroup** [comment]
https://vocal-truffle-4ec4c8.netlify.app/

Is this the correct version now??

**Comment by mistermantas** [comment]
no it's 5.3

latest is v5.6 - but it looks like if you are deploying from the button in the README file then that won't work

i'll fix that soon as I get the opportunity to, but there's no way to easily update without using the command line at the moment

**Comment by mistermantas** [comment]
well no your old site is 5.3

**Comment by FlexaGroup** [comment]
Okay.

**Comment by mistermantas** [comment]
try now with the same deploy to netlify or diff button, i updated cstate/example

**Comment by FlexaGroup** [comment]
Okay
