### ISSUE TITLE
Make RSS feed discoverable

### ISSUE THREAD

**Issue by SamWhited** [cstate/cstate#32]
**Is your feature request related to a problem? Please describe.**

I subscribe to the status page of services that I use or run myself via Atom (or RSS) feeds. Hugo generates an RSS feed for its categories, but if the feed is not made discoverable then readers will not know that it exists and can't use it.

**Describe the solution you'd like**

Add a link to the header that points to any alternative representations of the document (such as RSS):

    <link rel="alternate" type="application/rss+xml" href="http://localhost:1313/index.xml" title="My status" />

**Describe alternatives you've considered**

This is the standard way to make alternative representations of the document discoverable, there is no alternative solution.

**Patch**

In accordance with the PR template I did not make a pull request yet, but you can see the entirety of the work required on this page: https://gohugo.io/templates/rss/
A patch which can be used if desired is here: 33876f816a803b7fca26de1cd85265aa604838bb 

https://github.com/SamWhited/cstate/blob/33876f816a803b7fca26de1cd85265aa604838bb/layouts/partials/meta.html#L12-L14

**Comment by SamWhited** [comment]
> Thing is, I don’t use RSS at all, I’m not sure if this produces the wanted result. Would there be anything that needs changing apart from the default index.rss?

I don't think so; the default rss feed seems to work fine and the patch I linked makes it discoverable. Should I submit it as a PR? I'm using it on one of my own status pages right now.

**Comment by mistermantas** [comment]
Sure. I'm not sure when I'll merge it, but I approve of it.

**Comment by SamWhited** [comment]
Fixed in v3 (thanks!); apparently if you put the fixes line in the GitHub PR body instead of the commit message it doesn't auto close.
