### ISSUE TITLE
On the front page categories status is empty if components are ok. Would be nice to have it "Operational"

### ISSUE THREAD

**Issue by jouniso** [cstate/cstate#320]
By default status for components is empty and if there is issues in components, then there is status text after component. It would be nice to have "Operational" text displayed when everything is ok with all it's components.

On [code](https://github.com/cstate/cstate/blob/d0d39000c2d3eef82f63c8a6a00dd8b30ba6688a/layouts/partials/index/components.html#L113)
```
// By default, all is good but we change this value
// for progressively worse statuses
var highestLevelStatus = '';
```
It would be nice to have it default to 'ok'
```
var highestLevelStatus = 'ok';
```

Then categories that have all components in ok state would have Operational text even when they are closed.

![status](https://github.com/cstate/cstate/assets/23113678/36ab2e52-d1a4-4dbc-9650-62a8d0de6a6d)

**Comment by mistermantas** [comment]
hi, feel free to add this in a PR :)

**Comment by mistermantas** [comment]
this will be added in v6 :)
