### ISSUE TITLE
Recommended Hugo version? Rendering issue informationals in incident history with links

### ISSUE THREAD

**Issue by n-bux** [cstate/cstate#330]
**Describe the bug**
When running a cstate site (tried with cstate/example and our own installation) with hugo latest (0.139.3), informationals with URLs / `<a href..>` tags get a wrong line break plus indentation in the incident history (see screenshots below)

**Reproduction steps**
1. create issue with `informational: true` and including a markdown link or a URL
2. serve site with hugo latest  (0.139.3)
3. Scroll down to "Incident history"
4. Look at the preview of the first lines

(Content of test issue:

```md
---
title: Maintenance Announcement 
date: 2024-02-24 10:35:00 
informational: true
pin: true 
section: issue
---

We will shut down our network at midnight UTC on Feb 24. This does not affect the current status.

This is a [markdown test link](www.example.com). This is following text.

And this is a normal URL: https://www.test.de with following text.
```

**Expected behavior**
The Issue text shouldn't have line breaks before, nor strange indentation after (first) link. 

Also, (my opinion) the preview of the content should be without line breaks at all, just as behaviour with hugo 0.100.2 (see last screenshot)

**Screenshots**

Hugo latest:

![Eggsample-Status](https://github.com/user-attachments/assets/e2c83a8c-977f-41d4-b2aa-9aa6201a325f)
![Eggsample-Status2](https://github.com/user-attachments/assets/8adbae58-01df-45bc-b503-b020469be3a8)

Hugo 0.100.2
![Eggsample-Status_old](https://github.com/user-attachments/assets/d48db380-1374-4a82-ad80-c7d82290d0b9)

**Additional context**

tried this with hugo images from registry.gitlab as well as `peaceiris/actions-hugo@v2   with:    hugo-version: 'latest'` on Github.io

**Comment by mistermantas** [comment]
Hi, the last version wasn't tested with v0.139.x.

Seems like something broke / was deprecated in a new version since the last one I recall testing in was 0.98.x :)

**Comment by mistermantas** [comment]
https://github.com/gohugoio/hugo/commit/c0d15a2897be0bc9f6df2514f5a477b6df1fa0e5

this bug may still be present in hugo somehow with .Summary, strange.

**Comment by mistermantas** [comment]
I've simply chosen to remove descriptions for informational posts, at least for now. Will be pushed to v6.

**If you are using v5.\*, please use hugo v0.110 or earlier.**
