### ISSUE TITLE
Add RSS feed link to footer

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#35]
index.rss

**Comment by amintasvrp** [comment]
Hello @mistermantas. How can I help you ?

**Comment by mistermantas** [comment]
@amintasvrp This is not relevant to the issue. Furthermore, I know how to add links to a webpage lol.

**Comment by mistermantas** [comment]
Fixed in v3 staging

**Comment by SamWhited** [comment]
> Fixed in v3 staging

Is it? I don't think the PR ever got merged and I don't see an alternative implementation.

**Comment by mistermantas** [comment]
Locally, yes, an alternate implementation. Should probably close your PR tbh.

**Comment by SamWhited** [comment]
Works for me, I just didn't see it in the source. Thanks!
