### ISSUE TITLE
The version number in the footer is wrong for version 2.0.2.

### ISSUE THREAD

**Issue by metaa** [cstate/cstate#39]
**Describe the bug**
The version number in the footer is wrong (version `2.0.2` shows `2.0.1`).

**Reproduction steps**
1. Go to an up to date (`2.0.2`) cstate page.
2. Scroll down to the footer.
3. See error

**Expected behavior**
The correct version number would be displayed.

**Screenshots**
I don't think that's necessary. Take this instead:
https://github.com/cstate/cstate/blob/1bee071dfc3cf1493c730f1a6a069549399efdb0/layouts/partials/footer.html#L14-L14

**Desktop (please complete the following information):**
*Does not apply*

**Smartphone (please complete the following information):**
*Does not apply*

**Additional context**
*Does not apply*

**Comment by mistermantas** [comment]
Yeah do you think there's a point in this if I've already released that version? It wouldn't be 2.0.2 but like 2.0.3 if I patched it, even if it's wrong.

**Comment by mistermantas** [comment]
I've changed the string anyway, since it's probably a good idea. Thanks for the PR. 👌
