### ISSUE TITLE
Create official Docker image

### ISSUE THREAD

**Issue by whalehub** [cstate/cstate#50]
**Is your feature request related to a problem? Please describe.**
Docker solves the problem of easily deploying and updating a whole stack of web applications. Without an official Docker image, it's difficult to integrate cstate into an existing Docker software stack.

**Describe the solution you'd like**
I would like for you to provide an official Docker image, preferable one based on [automated builds](https://docs.docker.com/docker-hub/builds/) so you don't have to manually push a new image every time you make a change.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Edit:** Fixed URL.

**Comment by mistermantas** [comment]
I don't know Docker.

There is possibility for this, I've asked someone who knows Docker for help, but cState was literally not made to work like that, instead for Netlify.

**Comment by mistermantas** [comment]
should be fixed soon:tm:

![image](https://user-images.githubusercontent.com/11616378/51699662-fea2e080-2015-11e9-8938-2fc6130c250b.png)

**Comment by mistermantas** [comment]
Bad news! I’ve chosen to not support Docker for two good reasons:

1. cState is supposed to be hosted on Netlify, or GitHub Pages, or something like it. More environments complicate things for me — or maybe they don’t, I don’t know Docker, so I’ll just close this.
2. The person in the screenshot has tried helping with this before but I’m pretty sure I won’t be able to talk him into trying to do this again.

If someone else wants to help with this, I’d be fine with it. That person won’t be me though.
