### ISSUE TITLE
If there are no incidents, the status page doesn't build on Netlify

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#58]

**Comment by brandonlui19** [comment]
Yes, I am also getting the same problem

**Comment by mistermantas** [comment]
you should be able to fix the problem by just adding an incident.

**Comment by mistermantas** [comment]
newest release will fix this issue.

cause: there has to be a `content` folder. doesn’t matter if it’s empty. to avoid git from removing the folder, `.gitkeep` will be added to the exampleSite
