### ISSUE TITLE
Please update screenshots and demo title

### ISSUE THREAD

**Issue by onedrawingperday** [cstate/cstate#59]
Hello @mistermantas 

Can you please update the screenshots in the theme repo as well as the title to reflect the latest changes on the Hugo Themes showcase?

cc: @digitalcraftsman

**Comment by mistermantas** [comment]
... why?

Unless there's something I missed, I have nothing to change.

**Comment by onedrawingperday** [comment]
Why do you think?

![screenshot_2019-02-26 cstate](https://user-images.githubusercontent.com/7918298/53405932-9737d200-39c1-11e9-933b-72e06e746205.png)
![screenshot_2019-02-26 hugo themes](https://user-images.githubusercontent.com/7918298/53405933-97d06880-39c1-11e9-9173-e50926410ab9.png)

**Comment by mistermantas** [comment]
umm. yeah but screenshots and illustrations are not the same thing. the readme still has the same illustration as on the hugo showcase so it's not like I'm being inconsistent or anything.
