### ISSUE TITLE
Netlify error when viewing incident: layoutPostDateEnd.getYear is not a function

### ISSUE THREAD

**Issue by pauby** [cstate/cstate#63]
**Describe the bug**
When viewing an incident the following error is displayed in the right hand pane:

```
Error
There's been an error - please report it.

Details
TypeError: layoutPostDateEnd.getYear is not a function
```

I'm not sure at this stage what it affects but it says it's to be reported.

**Reproduction steps**
1. Login in to the site on Netlify;
2. View an existing (resolved in thsi case) incident

**Expected behavior**
No error to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/12760779/54632418-f8f5d400-4a75-11e9-9bfc-a92be5419907.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Version 73.0.3683.75

**Comment by pauby** [comment]
Is this perhaps related to #57 (I didn't add to that as it was a slightly different error).

**Comment by mistermantas** [comment]
It's related but not the same. It pertains to the way the preview is rendered. There's a JS check that gets the date and tries to simulate what the live site would look like. I'll try to get a better fix in place since this has been an ongoing issue ever since I introduced those new previews

**Comment by mistermantas** [comment]
The dev branch doesn’t have this code (apparently I had fixed this before lol) so I’ll close this issue and I can reopen it if things still aren’t working. 🙂

**Comment by pauby** [comment]
This is still an issue with 3.0.1.

![image](https://user-images.githubusercontent.com/12760779/56026999-2f3d1100-5d0d-11e9-8aad-b1232a758479.png)

**Comment by mistermantas** [comment]
@pauby least it's a different issue!

what you can do now as a stopgap is go into `static/admin/index.html` and get rid of the `<script>` tag(s) with this custom preview code in it cause you should only really need the `<script src` ones for the CMS to work.

I'll try setting this up again another week, right now I'm going on a trip. I've likely implemented the dates wrong and why they were working locally for me is a mystery at this point.

**Comment by pauby** [comment]
@mistermantas I just wanted to come back here to say this is fixed now. Thank you for your time on this. It is very much appreciated!
