### ISSUE TITLE
Add Portuguese Language

### ISSUE THREAD

**Issue by dmcclccam** [cstate/cstate#68]
**Describe the solution you'd like**
A translation for the Portuguese language.

**Comment by mistermantas** [comment]
Can you translate cState?

**Comment by mistermantas** [comment]
If so, make a PR to the `dev` branch.

there’s really no other way to add another language.

https://github.com/cstate/cstate/tree/dev

**Comment by dmcclccam** [comment]
@mistermantas Sure! Working on it here: https://github.com/un-banked/cstate/tree/i18n-add-pt

**Comment by mistermantas** [comment]
Awesome. I’ll be waiting for your PR :)
