### ISSUE TITLE
Incidents at the top of the page

### ISSUE THREAD

**Issue by Stoovey** [cstate/cstate#74]
Hey,

Is it possible to remove the 'Incidents' at the top of the page, so it only shows the product/service with the 'status' and then the incident history at the bottom?

Thanks,
Steve

**Comment by mistermantas** [comment]
There is no such feature in the config, but what you can do is override the index.html in layouts and remove the Announcements (if I recall correctly) partial which is loaded.

would you want such a feature? Rather, is there a good reason for implementing itm
________________________________

**Comment by Stoovey** [comment]
I'd love to do that, but my themes is a submodule of your git repo, so I can't actually edit it :(

**Comment by mistermantas** [comment]
you can, have you taken a look at the developer section of the wiki?

If your theme is in themes/cstate blah blah then you can do layouts/index.html and override it

BUT THERE'S ONE THING. with each update you'll need to update the index.HTML file if it adds new features or changes things around
________________________________

**Comment by Stoovey** [comment]
I edited my previous comment :) Didn't realize you'd be so quick!

Thanks!

**Comment by mistermantas** [comment]
you're very much welcome. I'm on email so I guess the edits don't show up
________________________________
