### ISSUE TITLE
Invalid Discord Invite in README

### ISSUE THREAD

**Issue by pnfcre** [cstate/cstate#76]
**Describe the bug**
There's a badge to join the Discord support guild for this project in [README.md](https://github.com/cstate/cstate/blob/master/README.md).
However, the invite seems to be invalid.

**Reproduction steps**
1. Open the [README.md](https://github.com/cstate/cstate/blob/master/README.md).
2. Click the badge saying "Discord Support" under the header image.

**Expected behavior**
Invite should be valid and I should be able to join the Discord guild.

**Screenshots**
![image](https://user-images.githubusercontent.com/24176136/57620372-e1742c80-7588-11e9-9133-1d55e70b6877.png)

**Desktop:**
 - OS: Chrome OS Version 72.0.3626.122 (Official Build) (64-bit)
 - Browser: Chrome
 - Version: 72.0.3626.122

**Comment by mistermantas** [comment]
https://discord.gg/<https://discord.gg/zYCjzys>zYCjzys<https://discord.gg/zYCjzys>

it's not possible for me to make a change to the **dev** branch right now cause I'm away from my pc so if you want to change the URL to that, knock yourself out & I'll merge the pr
________________________________

**Comment by pnfcre** [comment]
Ah, I should've made the change to the `dev` branch?

**Comment by mistermantas** [comment]
yes
________________________________

**Comment by pnfcre** [comment]
There we go 👍
