### ISSUE TITLE
Categories: hidden components

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#8]
Subsystems are basically components housed within components. They are hidden under an expand icon, like **[+]**, and can only change status by incident. ![Example](https://user-images.githubusercontent.com/11616378/42408941-7298f77e-81db-11e8-8c67-430277065fe3.png)

This may be difficult to implement in time for v2 but should be considered. The system for how incidents & components work at the moment is simple enough but would get complicated with subcomponents.

**Comment by mistermantas** [comment]
Renaming this to categories. Would be less complicated.

**Comment by mistermantas** [comment]
I've come to the conclusion that the only way to do this properly is to have a boolean for whether you want categories or not. Otherwise it makes the templating... erm... hard.

Might be one of the last things for v3.

**Comment by Stoovey** [comment]
When will this be released?

**Comment by mistermantas** [comment]
@Stoovey asap. It's scheduled for the next release

**Comment by Stoovey** [comment]
@mistermantas 
Great - look forward to it. 

When is that?

**Comment by mistermantas** [comment]
@Stoovey I'm glad you're excited but this project is provided on an as is basis. In other words, I'm not a company, this is just an unprofitable side thing for me (might want to open donations however I hardly think anyone would want to donate). But don't get me wrong, I like working on the project from time to time and updating it is important for the evergrowing community. Right now I've locally got categories working but there's no expanding / closing so it's just headings. Was thinking of IE8+ and JS less (or something like that) ways to make everything work as expected especially for people who don't want categories at all too
