### ISSUE TITLE
Removing auto-refresh

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#80]
It doesn’t seem to be doing anything — twice I saw it just tick past the 5 minute mark while the window was open — so it’s just an extra unhelpful gimmick.

Maybe the code needs to be fixed / edited?

Removing in v4.1 / v5 and probably not replacing it with anything else.

(Also this is more like _Discussion wanted_, not help necessarily.)

**Comment by WOLFI3654** [comment]
Hey, I'll take care of this

**Comment by mistermantas** [comment]
@WOLFI3654 No need. I've done this already.

**Comment by WOLFI3654** [comment]
Why do you put it up for hacktober then

**Comment by mistermantas** [comment]
Sorry! When I created the issue it wasn't removed but I did it myself just a few moments ago. If you'd like you can submit a translation to the dev branch or suggest other changes ♥️
