### ISSUE TITLE
Question: integration with automatic monitoring

### ISSUE THREAD

**Issue by jawn** [cstate/cstate#86]
Hi,

I'm probably not [seeing the forest for the trees](https://en.wiktionary.org/wiki/see_the_forest_for_the_trees).

It is unclear to me whether any out of the box integration is provided to support automatic monitoring of e.g. services, APIs etc. 

If not, what approaches are used to automatically update cstate when detected outages occur?

**Comment by mistermantas** [comment]
cState is not updated automatically, sorry.

If you use something like Uptime Robot, if I remember correctly, you can add HTML that shows the monitoring stats.

But incidents and the statuses (“Operational,” “Disrupted”) are meant to be updated manually.

Maybe you could use the Netlify/GitHub/GitLab API, but I’m not going to support such a thing personally.

Unless you have some other question, that’s all there is to it. :)

**Comment by jawn** [comment]
Thanks for the quick response.

I was confused by the Pollling... status in this screenshot. Would that be some javascript check as part of the static content?
![image](https://user-images.githubusercontent.com/1705112/67485381-35bc2600-f66a-11e9-972a-8f3fc3641229.png)

**Comment by mistermantas** [comment]
@jawn you could implement that with a 3rd party script, essentially, yes. but it's not built in. the illustration is a little bit misleading...

**Comment by jawn** [comment]
Do you want me to send a PR to update the illustration with a more realistic one for the hosted example?

**Comment by mistermantas** [comment]
@jawn What would you change exactly? I think I can update it myself if I can find where I made the illustration in figma.

**Comment by jawn** [comment]
I would replace the screenshot with something like this, taken from https://cstate.mnts.lt

![image](https://user-images.githubusercontent.com/1705112/67493894-af5b1080-f678-11e9-9fdd-c9e18e7018ee.png)

**Comment by mistermantas** [comment]
I wanna keep the illustration, maybe just remove the polling stuff. It does look nice.
________________________________

**Comment by mistermantas** [comment]
![Group 6](https://user-images.githubusercontent.com/11616378/67637319-06175300-f8e2-11e9-9a5b-2460e1b2a4e9.png)
Here you go. This should be less misleading, maybe even look a bit nicer :)

**Comment by gabrielsclimaco** [comment]
@jawn did you manage to implement the atomatic update? I'm trying to do the same thing, maybe we can help each other :wink:

**Comment by jawn** [comment]
Hi @gabrielsclimaco

No, I haven't looked into that.
