### ISSUE TITLE
Status is not defaulting to Operational (Netlify CMS)

### ISSUE THREAD

**Issue by SemiClickbait** [cstate/cstate#90]
**Describe the bug**
None of the system components are defaulting to Operational.

**Reproduction steps**
1. Go to Netlify CMS (that’s what I use personally)
2. Delete all active events (or mark them as resolved)
3. Save and Publish

**Expected behavior**
It is supposed to default to Operational, as [seen here](https://filebin.net/w43b0p37phuojh6a/3D7DAC23-6DE9-4691-B6D3-5081F9D882BB.jpeg?t=x4e5dyvu).

**Screenshots**
 [Click here](https://filebin.net/hr2t960z7afv8apw/C3B4B48A-A9CE-436D-AB48-106BA045DEFC.jpeg?t=qyx7n52i)

**Smartphone (please complete the following information):**
 - Device: iPad 5th Generation
 - OS: ios 13.3 developer beta
 - Browser: Safari
 - Version: 13.3

**Comment by mistermantas** [comment]
Hi!

Thanks for trying cState. This is a known issue that will be fixed in v4.

See #83

For a temporary fix, you can go to your GitHub repository and put the HEX code in quotes, from `ok: 008000` to `ok: "008000"`. Zeros do not work properly with Netlify CMS and Hugo by default.

Have you got any more questions?

**Comment by SemiClickbait** [comment]
Nope! Thanks!

**Comment by SemiClickbait** [comment]
I've added the quotes, and it shows Operational, but no color. Is there a workaround?

**Comment by mistermantas** [comment]
@SemiClickbait Can you send a link, please and your config file?

**Comment by SemiClickbait** [comment]
Hey! I just fixed the coloring. I just used the default coloring, and it works now.
