### ISSUE TITLE
Generate a badge for inclusion in other sites

### ISSUE THREAD

**Issue by cbergmann** [cstate/cstate#91]
**Is your feature request related to a problem? Please describe.**
I currently redesign our infrastructure documentation. It is in the form of a Wiki page. It would be cool if we could add a badge to the home page of that wiki that shows the status of our infrastructure and links to the status page.

**Describe the solution you'd like**
I suggest that a png file is generated that contains the color and name of the current overall status. Such a image could be included in other pages and would always represent the current overall status of the infrastructure. Something like this: https://img.shields.io/badge/IT--status-All_OK-brightgreen

**Describe alternatives you've considered**
I could not find a alternative 

**Additional context**
None

**Comment by cbergmann** [comment]
After I think a little longer a PNG file would be not the optimal option. A SVG file would be more easy to generate and would look better on different screens.

**Comment by mistermantas** [comment]
I'm not really sure how to implement something like that. I definitely want to have features like this.

There's a read only API in v4 so you can check the status if you need JSON information.

Shields.io is cool but I'm not sure how useful it is.

1. How would the design of the shields look like?
2. Once that's figured out, how do you deliver that based on the status?
3. Problems with translation. Images can't be premade but generated each time unless an English only solution is actually acceptable

**Comment by cbergmann** [comment]
Hi, I had some spare time today and hacked something together. I am new in SVG and in hugo templating so I don't know if it is OK from a quality of code standpoint. I also don't know exactly if it needs a update to the config or it can somehow put into the theme. To use it in the current form you have to add the following code to the config 

```
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
```

you also have to add `svg` to the output of home like so:

```
outputs:
  page:
    - html
  section:
    - html
    - rss
  home:
    - html
    - json
    - rss
    - svg
```

Then you can put the attached file as index.svg in the layouts folder.

[index.svg](https://github.com/cstate/cstate/files/3961750/index.svg.txt)

That should generate a index.svg file.

It would be cool if you could look at the code and give some feedback.

**Comment by mistermantas** [comment]
The thing is, if it works for you — go ahead and use it!

Do you have a repository so I can clone that and run the code?

**Comment by cbergmann** [comment]
This is our status repo
https://github.com/proventa/status

The result can be found on https://status.proventa.io

**Comment by cbergmann** [comment]
You can see the svg here:https://status.proventa.io/index.svg

**Comment by mistermantas** [comment]
Looks great.

My hope is to get v4 out the door before 2020, so I don't think I can add any features in the meantime.

In 2020, this could be a great addition. Frankly, if your code:

1. works
2. has at least a few comments
3. is spaced out instead of in all one big pile

then I'd probably merge a PR like that.

The current thing you have going with the SVG seems like a good solution, but ideally I'd like to add multiple styles (which is possible here, of course) and, if also possible, not require config changes.

SVGs are basically HTML in markup so you could _maybe_ get away without that, but I have no idea, that seems like a hack more than anything.

I come back to this project on and off, so I struggle with those 3 points myself, but that's the ideal situation. After v4 is out, by all means — make a PR!

**Comment by cbergmann** [comment]
Hi, ok that sounds like a plan. I have a solution that works for me so I am also not in a rush. Feel free to notify me whenever you find time to work on it. I might find time until then to prepare a PR.

have a great and relaxing holiday season.
Clemens

**Comment by mistermantas** [comment]
v4 is out, so I did this since I had the motivation so why not

https://github.com/cstate/cstate/wiki/Badges

https://github.com/cstate/cstate/blob/dev/layouts/index.svg

**Comment by mistermantas** [comment]
v4.1 will include this. Instructions in the wiki show how to enable this.
