### ISSUE TITLE
Advertising cState

### ISSUE THREAD

**Issue by mistermantas** [cstate/cstate#92]
Where could cState be advertised? I know it's some alternativeto.net site or something like it, I've made a Product Hunt entry before but it didn't really go off that well. Maybe UpLabs?

If you have any suggestions, please let me! cState is growing, I'd say at a healthy pace, but with the release of v4, I'd like to make some marketing images, share what I (and with the help of a few contributors) has changed.

**Comment by n1trux** [comment]
You could create a PR for the [awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted).

**Comment by mistermantas** [comment]
Lovely suggestion! Will do.
