### ISSUE TITLE
rename to something searchable

### ISSUE THREAD

**Issue by n1trux** [cstate/cstate#94]
[C-States are already a thing in IT](https://en.wikichip.org/wiki/acpi/c-states), so I think cstate is hard to search for unless you add "status page" to the request.

`cstatepage` (current state page?) would be much easier to google.

**Comment by mistermantas** [comment]
That looks so incredibly awkward, though.

I'm not sure if it would help with search either. cState is already the third result for me. 

![](https://i.imgur.com/Pj0OvKl.jpg)
