### ISSUE TITLE
some fonts dont include  BLACK MEDIUM RIGHT-POINTING TRIANGLE CENTRED and other symbols

### ISSUE THREAD

**Issue by EmilioD** [cstate/cstate#96]
**Describe the bug**
on some systems (so far linux fully tested), the default system fonts do not include some symbols used in cstate.

**Expected behavior**
symbols choosen would work across most/all systems. Instead the standard unicode BOX is shown. 

**Desktop (please complete the following information):**
 - OS: RHEL 7.x 8.X and Ubuntu 16.04
 - Browser all browswers

**Additional context**
while this is not techincally a cstate issue (its a font issue), it would make sense to offer a way to make this not dependiant on symbols - ie RIGHT ARROW becomes [+] and down arrow becomes [-] or similar

**Comment by mistermantas** [comment]
Do all default fonts not support this character? Perhaps there are others that would work.

**Comment by mistermantas** [comment]
I should also mention that there are other maybe not as often used Unicode characters in cState, some of which I would not know how to replace. Does emoji work with these fonts ,too or no?

**Comment by kfox1111** [comment]
I have ran into this issue also. Centos8 firefox/chrome are effected. Chrome just shows a black box. Firefox shows a box with the unicode numbers in it. An older version of windows with firefox does the same. older ie has the same behavior as chrome.

**Comment by mistermantas** [comment]
so the category one is most obvious, i can change that. what are other symbols? i remember that the 'issue ongoing' text for the issues list has shapes next to it to indicate the priority (which was an afterthought anyway), should that be removed or kept?

**Comment by mistermantas** [comment]
The newly added Unicode symbols date back to the first renditions of Unicode in 1993 and use these symbols:
