### ISSUE TITLE
System name override

### ISSUE THREAD

**Issue by kfox1111** [cstate/cstate#98]
I've got several clusters that each have the same kinds of services. For example, Kubernetes Cluster A, and Kubernetes Cluster B.
Each cluster has services such as:
* API
* Ingress
* Networking
etc.

My initial thought would be to map Cluster to catagoies and then service to systems.
This mostly works, but the ui gets redundant:
"Kubernetes Cluster A"
* "A API"
* "A Ingress

"Kubernetes Cluster B"
* "B API"
* "B Ingress

because the servers name field must be unique.
While partials allow you to inject information into the box, it doesn't let you override the name thats displayed.

Can we get a new field like displayName thats optional that will be the content of the box if specified, otherwise falls back to displaying name?

**Comment by kfox1111** [comment]
Looks like this can be added pretty easily:
layouts/partials/index/components.html update:
{{ .name }}
to be
{{ default .displayName .name }}

Want a PR?

**Comment by mistermantas** [comment]
Sure
